### ISSUE TITLE
Invalid 'subject_token' value: invalid (ShopifyCli::OAuth::Error)

### ISSUE THREAD

**Issue by lavecart** [Shopify/shopify-cli#1091]
`C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-1.6.0/lib/shopify-cli/oauth.rb:169:in `post_token_request': Invalid 'subject_token' value: invalid (ShopifyCli::OAuth::Error)
`

While I am pasting the url then it is giving me this error. What is the problem? I am using Windows.

**Comment by paulomarg** [comment]
Hi @lavecart, couple of things:

- Since this is a Ruby error, I'm assuming this is a problem with a Rails app created with the CLI? If that is the case, could you please report your issue in https://github.com/Shopify/shopify_app?
- We'll also need more details on how you reached this error. A few things that might help:
  - Is this a new app? Have you made any changes to it?
  - What version of Ruby / Rails are you using? The `shopify system` command prints out relevant information about your project.
  - When does that error happen? What did you have to do for it to happen?

Thanks!

**Comment by richgilbank** [comment]
@paulomarg Same issue here trying a fresh install of the CLI (`gem install ...`) to create a Node app. Repro steps:
- Install CLI (`gem install shopify-cli`)
- `shopify create node`
- Enter app name, select "Public app"
- Follow the auth link, select an account to login with. Page redirects to this:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/1245284/112683606-32712f00-8e48-11eb-867d-2367b400b49c.png">

- close tab, return to console. Output:

```
Traceback (most recent call last):
        42: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/bin/shopify:32:in `<main>'
        41: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        40: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        39: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/bin/shopify:33:in `block in <main>'
        38: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/core/entry_point.rb:42:in `call'
        37: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/core/monorail.rb:20:in `log'
        36: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
        35: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/core/executor.rb:15:in `call'
        34: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        33: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        32: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        31: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        30: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        29: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        28: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        27: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        26: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        25: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        24: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        23: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        22: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        21: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/commands/create.rb:8:in `call'
        20: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/command.rb:19:in `call'
        19: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/sub_command.rb:12:in `call'
        18: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/project_types/node/commands/create.rb:18:in `call'
        17: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/form.rb:13:in `ask'
        16: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/project_types/node/forms/create.rb:13:in `ask'
        15: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/task.rb:7:in `call'
        14: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/tasks/select_org_and_shop.rb:14:in `call'
        13: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/tasks/select_org_and_shop.rb:42:in `get_organization'
        12: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/tasks/select_org_and_shop.rb:31:in `organizations'
        11: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/partners_api/organizations.rb:6:in `fetch_all'
        10: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/partners_api.rb:48:in `query'
         9: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/partners_api.rb:63:in `authenticated_req'
         8: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/partners_api.rb:49:in `block in query'
         7: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/partners_api.rb:74:in `api_client'
         6: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/partners_api.rb:80:in `access_token'
         5: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/db.rb:87:in `get'
         4: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/partners_api.rb:81:in `block in access_token'
         3: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/partners_api.rb:93:in `authenticate'
         2: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/oauth.rb:43:in `authenticate'
         1: from /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/oauth.rb:148:in `request_exchange_token'
/usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1/lib/shopify-cli/oauth.rb:169:in `post_token_request': Invalid 'subject_token' value: invalid (ShopifyCli::OAuth::Error)
```

**System Info**

```
Shopify App CLI
               ROOT = /usr/local/lib/ruby/gems/2.5.0/gems/shopify-cli-1.7.1

Ruby (via RbConfig)
  /usr/local/Cellar/ruby/2.5.1/bin/ruby
  x86_64-apple-darwin17.3.0 - RbConfig["host"]
  ruby-2.5.0                - RbConfig["RUBY_VERSION_NAME"]

Commands
  ✓ git, /usr/local/bin/git
  ✓ curl, /usr/bin/curl
  ✓ tar, /usr/bin/tar
```

**Comment by sukumar-varma** [comment]
I was able to bypass this issue by opening the authentication link in a private/incognito browser window and re logging into Shopify. I believe clearing your browser cache might also work. Authentication was successful and I was able to create an app.

**Comment by s-chand** [comment]
I just bumped into this. Yes, clearing my cache worked. Thanks @sukumar-varma

**Comment by mdmathewdc** [comment]
This issue still persists. Tried clearing browser cache but doesn't work.

**Comment by MarceloDiasSchneider** [comment]
I fix this problem making login in My Shopify Partner Account.
Settings > CLI Token > Manage tokens > Generate new token
