### ISSUE TITLE
CLI connect command fails

### ISSUE THREAD

**Issue by langdag** [Shopify/shopify-cli#1235]
# Issue summary

Write a short description of the issue here ↓
I am trying to connect my project with a store created in Shopify Partner Dashboard. But I am getting the error. The error happens regardless of being authenticated or not. If I run "shopify logout" and then "shopify connect" it still fails but only after authentication. Also noticed that "shopify create" fails to , with message "No partner organizations available." Somehow it can't see my organization. Not sure if this two errors connected together.

## Expected behavior

What do you think should happen?
1. Run shopify connect
2. CLI should successfully complete the connection

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

**shopify connect**
```
! This app appears to be already connected

? What type of project would you like to connect? (Choose with ↑ ↓ ⏎, filter wit? What type of project would you like to connect? (You chose: Ruby on Rails App)

! Warning: if you have connected to an app in production, running serve may update the app URL and cause an outage.                                             
This command ran with ID: 19263

Please include this information in any issues/report along with relevant logs

Traceback (most recent call last):


        31: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/bin/shopify:32:in `<main>'
	30: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	29: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	28: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/bin/shopify:33:in `block in <main>'
	27: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/lib/shopify-cli/core/entry_point.rb:42:in `call'
	26: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/lib/shopify-cli/core/monorail.rb:20:in `log'
	25: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
	24: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/lib/shopify-cli/core/executor.rb:15:in `call'
	23: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	22: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	21: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	20: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	19: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
	18: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	17: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	16: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	15: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	14: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	13: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	12: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	11: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	10: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/lib/shopify-cli/commands/connect.rb:9:in `call'
	 9: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/lib/shopify-cli/command.rb:25:in `call'
	 8: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/lib/shopify-cli/commands/connect.rb:28:in `call'
	 7: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/lib/shopify-cli/sub_command.rb:12:in `call'
	 6: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/lib/project_types/rails/commands/connect.rb:10:in `call'
	 5: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/lib/shopify-cli/commands/connect.rb:44:in `default_connect'
	 4: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/lib/shopify-cli/task.rb:7:in `call'
	 3: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/lib/shopify-cli/tasks/ensure_env.rb:17:in `call'
	 2: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/lib/shopify-cli/tasks/ensure_env.rb:32:in `fetch_org'
	 1: from /home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:100:in `ask'
/home/satoshy/.rvm/gems/ruby-2.5.8/gems/shopify-cli-1.10.0/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:192:in `ask_interactive': insufficient options (ArgumentError)
```

## Steps to reproduce the problem

1. gem install shopify-cli
2. shopify connect

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: Ruby On Rails
- Operating System: Ubuntu 18.04
- Shell: zsh
- Ruby version (ruby -v): 2.5.8

**Comment by t-kelly** [comment]
Hey @langdag -- I was able to reproduce this when I was logged in with an account that was not associated to a partner account. After calling `shopify logout`, calling `shopify connect`, and then logging in with an account that is associated to a partner account, this error went away.
