### ISSUE TITLE
shopify rails create with postgres returns Gem::Ext::BuildError 

### ISSUE THREAD

**Issue by artyrcheek** [Shopify/shopify-cli#1329]
# Issue summary
When i run `shopify rails create` and select postgresql as database, i get the error:
`Gem::Ext::BuildError: ERROR: Failed to build gem native extension.`
When I cd into the app and run `bundle`, everything works fine
```
make failed, exit code 2

 Gem files will remain installed in /usr/local/Cellar/shopify-cli/2.0.1/gems/pg-1.2.3 for inspection.
 Results logged to /usr/local/Cellar/shopify-cli/2.0.1/extensions/x86_64-darwin-20/3.0.0/pg-1.2.3/gem_make.out

 An error occurred while installing pg (1.2.3), and Bundler cannot continue.
 Make sure that `gem install pg -v '1.2.3' --source 'https://rubygems.org/'` succeeds before bundling.

 In Gemfile:
   pg
          run  bundle binstubs bundler
 Could not find gem 'pg (>= 0.18, < 2.0)' in rubygems repository https://rubygems.org/ or installed locally.
 The source does not contain any versions of 'pg'
```

## Actual behavior

Full error: 
```
┃ Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
┃
┃     current directory: /usr/local/Cellar/shopify-cli/2.0.1/gems/pg-1.2.3/ext
┃ /Users/arthurcheek/.rvm/rubies/ruby-3.0.0/bin/ruby -I /Users/arthurcheek/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0 -r ./siteconf20210701-1017-ytzt41.rb
┃ extconf.rb --with-pg-config\=/Applications/Postgres.app/Contents/Versions/9.4/bin/pg_config
┃ Using config values from /Applications/Postgres.app/Contents/Versions/9.4/bin/pg_config
┃ sh: /Applications/Postgres.app/Contents/Versions/9.4/bin/pg_config: No such file or directory
┃ sh: /Applications/Postgres.app/Contents/Versions/9.4/bin/pg_config: No such file or directory
┃ checking for libpq-fe.h... yes
┃ checking for libpq/libpq-fs.h... yes
┃ checking for pg_config_manual.h... yes
┃ checking for PQconnectdb() in -lpq... yes
┃ checking for PQsetSingleRowMode()... yes
┃ checking for PQconninfo()... yes
┃ checking for PQsslAttribute()... yes
┃ checking for PQresultVerboseErrorMessage()... yes
┃ checking for PQencryptPasswordConn()... yes
┃ checking for PQresultMemorySize()... yes
┃ checking for timegm()... yes
┃ checking for rb_gc_adjust_memory_usage()... yes
┃ checking for unistd.h... yes
┃ checking for inttypes.h... yes
┃ checking for C99 variable length arrays... yes
┃ creating extconf.h
┃ creating Makefile
┃
┃ current directory: /usr/local/Cellar/shopify-cli/2.0.1/gems/pg-1.2.3/ext
┃ make "DESTDIR=" clean
┃
┃ current directory: /usr/local/Cellar/shopify-cli/2.0.1/gems/pg-1.2.3/ext
┃ make "DESTDIR="
┃ compiling gvl_wrappers.c
┃ compiling pg.c
┃ compiling pg_binary_decoder.c
┃ compiling pg_binary_encoder.c
┃ compiling pg_coder.c
┃ compiling pg_connection.c
┃ compiling pg_copy_coder.c
┃ compiling pg_errors.c
┃ compiling pg_record_coder.c
┃ compiling pg_result.c
┃ pg_result.c:1590:58: warning: 'rb_cData' is deprecated: by: rb_cObject.  Will be removed in 3.1. [-Wdeprecated-declarations]
┃         rb_cPGresult = rb_define_class_under( rb_mPG, "Result", rb_cData );
┃                                                                 ^
┃ /Users/arthurcheek/.rvm/rubies/ruby-3.0.0/include/ruby-3.0.0/ruby/internal/core/rdata.h:173:18: note: expanded from macro 'rb_cData'
┃ #define rb_cData rb_cData()
┃                  ^
┃ /Users/arthurcheek/.rvm/rubies/ruby-3.0.0/include/ruby-3.0.0/ruby/internal/core/rdata.h:166:1: note: 'rb_cData' has been explicitly marked deprecated
┃ here
┃ RBIMPL_ATTR_DEPRECATED(("by: rb_cObject.  Will be removed in 3.1."))
┃ ^
┃ /Users/arthurcheek/.rvm/rubies/ruby-3.0.0/include/ruby-3.0.0/ruby/internal/attr/deprecated.h:32:53: note: expanded from macro 'RBIMPL_ATTR_DEPRECATED'
┃ # define RBIMPL_ATTR_DEPRECATED(msg) __attribute__((__deprecated__ msg))
┃                                                     ^
┃ 1 warning generated.
┃ compiling pg_text_decoder.c
┃ compiling pg_text_encoder.c
┃ compiling pg_tuple.c
┃ compiling pg_type_map.c
┃ compiling pg_type_map_all_strings.c
┃ compiling pg_type_map_by_class.c
┃ compiling pg_type_map_by_column.c
┃ compiling pg_type_map_by_mri_type.c
┃ compiling pg_type_map_by_oid.c
┃ compiling pg_type_map_in_ruby.c
┃ compiling pg_util.c
┃ linking shared-object pg_ext.bundle
┃ ld: warning: argument missing after -rpath
┃ ld: file not found: dynamic_lookup
┃ clang: error: linker command failed with exit code 1 (use -v to see invocation)
┃ make: *** [pg_ext.bundle] Error 1
┃
┃ make failed, exit code 2
┃
┃ Gem files will remain installed in /usr/local/Cellar/shopify-cli/2.0.1/gems/pg-1.2.3 for inspection.
┃ Results logged to /usr/local/Cellar/shopify-cli/2.0.1/extensions/x86_64-darwin-20/3.0.0/pg-1.2.3/gem_make.out
┃
┃ An error occurred while installing pg (1.2.3), and Bundler cannot continue.
┃ Make sure that `gem install pg -v '1.2.3' --source 'https://rubygems.org/'` succeeds before bundling.
┃
┃ In Gemfile:
┃   pg
┃          run  bundle binstubs bundler
┃ Could not find gem 'pg (>= 0.18, < 2.0)' in rubygems repository https://rubygems.org/ or installed locally.
┃ The source does not contain any versions of 'pg'
┃        rails  webpacker:install
┃ /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:285:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'pg (>= 0.18, < 2.0)' in rubygems repository https://rubygems.org/ or installed locally. (Bundler::GemNotFound)
┃ The source does not contain any versions of 'pg'
┃ 	from /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:253:in `each'
┃ 	from /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:253:in `verify_gemfile_dependencies_are_found!'
┃ 	from /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:50:in `start'
┃ 	from /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:23:in `resolve'
┃ 	from /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler/definition.rb:287:in `resolve'
┃ 	from /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler/definition.rb:191:in `specs'
┃ 	from /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler/definition.rb:260:in `specs_for'
┃ 	from /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler/definition.rb:242:in `requested_specs'
┃ 	from /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler/runtime.rb:91:in `block in definition_method'
┃ 	from /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler/runtime.rb:20:in `setup'
┃ 	from /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler.rb:149:in `setup'
┃ 	from /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler/setup.rb:20:in `block in <top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler/ui/shell.rb:136:in `with_level'
┃ 	from /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler/ui/shell.rb:88:in `silence'
┃ 	from /usr/local/Cellar/shopify-cli/2.0.1/gems/bundler-2.2.21/lib/bundler/setup.rb:20:in `<top (required)>'
┃ 	from <internal:/Users/arthurcheek/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
┃ 	from <internal:/Users/arthurcheek/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
┃ 	from /Users/arthurcheek/Desktop/bts/shopify_apps/link_made_super/config/boot.rb:3:in `<top (required)>'
┃ 	from bin/rails:3:in `require_relative'
┃ 	from bin/rails:3:in `<main>'
```

(sorry to not put this in a details tag but it wouldnt display correctly)

## Steps to reproduce the problem

1. run shopify rails create

## Specifications

- App type: Rails
- Operating System: Big Sur
- Shell: ZSH
- Ruby version (ruby -v): ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]

**Comment by mkevinosullivan** [comment]
👋🏻 This indicates that the installation of the `pg` gem failed while trying to compile the native extensions.  Usually this is because the development headers for postgres can't be found.

How have you installed postgres on your system?  `brew` or another means?  The build above is looking for `/Applications/Postgres.app/Contents/Versions/9.4/bin/pg_config` and that file doesn't seem to exist.
