### ISSUE TITLE
Error cloning Dawn Theme

### ISSUE THREAD

**Issue by Zack-Iulla** [Shopify/shopify-cli#1337]
# Issue summary

Shopify-cli installed without any problems but When trying to clone dawn sample theme with `shopify theme init
` the below error shows

## Expected behavior

Theme cloneed

## Actual behavior

Below error showing
"`C:\ShopifyTheme>shopify theme init
? Theme name
<detail>> DAAS</detail>

┏━━ Cloning https://github.com/Shopify/dawn.git into DAAS... ━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃                                                                           0%
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.01s) ━━━
This command ran with ID: 24396
Please include this information in any issues/report along with relevant logs
C:/Ruby30-x64/lib/ruby/3.0.0/open3.rb:221:in `spawn': No such file or directory - git (Errno::ENOENT)
        from C:/Ruby30-x64/lib/ruby/3.0.0/open3.rb:221:in `popen_run'
        from C:/Ruby30-x64/lib/ruby/3.0.0/open3.rb:102:in `popen3'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/git.rb:126:in `block in clone_progress'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-ui/lib/cli/ui/progress.rb:34:in `progress'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/git.rb:122:in `clone_progress'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/git.rb:51:in `block in clone'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/git.rb:50:in `clone'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/project_types/theme/commands/init.rb:29:in `clone'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/project_types/theme/commands/init.rb:15:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/sub_command.rb:13:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/command.rb:19:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/core/executor.rb:15:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/core/monorail.rb:32:in `log'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/shopify-cli/core/entry_point.rb:23:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/bin/shopify:33:in `block in <main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/bin/shopify:32:in `<main>'</details>` "

## Steps to reproduce the problem

1.shopify theme init

## Specifications

- App type: Shopify-cli
- Operating System: Windows 10
- Shell:
- Ruby version (ruby -v): ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x64-mingw32]

**Comment by Zack-Iulla** [comment]
That worked Smooth as cutting butter. but when I run Shopify theme serve it
says I have no authorisation to edit themes on zattesting.myshopify.com.

• shopify theme init

? Theme name
> DAAS
┏━━ Cloning https://github.com/Shopify/dawn.git into DAAS...
━━━━━━━━━━━━━━━━━━━
┃
100%
┗━━ √ Cloned into DAAS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
(2.67s) ━━━

• shopify login --store zattesting.myshopify.com

Logged into store zattesting.myshopify.com in partner organization Zat
Creations

• shopify whoami

Logged into store zattesting.myshopify.com in partner organization Zat
Creations

•   shopify store

You're currently logged into zattesting.myshopify.com

•   shopify theme serve

X You are not authorized to edit themes on zattesting.myshopify.com.
Make sure you are a user of that store, and allowed to edit themes.

I know this isn't an error but what am I missing?

**Comment by Zack-Iulla** [comment]
Didn't work on the first try cleared the cookies and logged in again now
all good. I really appreciate your help
thank you!
