### ISSUE TITLE
shopify extension serve - undefined method `git_template' for nil:NilClass 

### ISSUE THREAD

**Issue by adamclasic** [Shopify/shopify-cli#1339]
# Issue summary

Write a short description of the issue here ↓

when running the command 'shopify extension serve', i am getting this error
`This command ran with ID: 34572
Please include this information in any issues/report along with relevant logs
/home/adam/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/shopify-cli-2.0.1/lib/project_types/extension/models/specification_handlers/default.rb:97:in `argo': undefined method `git_template' for nil:NilClass (NoMethodError)`

## Expected behavior
To run the extension in a local server.

## Specifications

- App type: Node/Theme extension
- Operating System: Ubuntu 20.04
- Shell: 
- Ruby version (ruby -v): 3.0.1

**Comment by bogdanrn** [comment]
+1 

```
This command ran with ID: 70665
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	31: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/bin/shopify:32:in `<main>'
	30: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	29: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	28: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/bin/shopify:33:in `block in <main>'
	27: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/lib/shopify-cli/core/entry_point.rb:23:in `call'
	26: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/lib/shopify-cli/core/monorail.rb:20:in `log'
	25: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
	24: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/lib/shopify-cli/core/executor.rb:15:in `call'
	23: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	22: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	21: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	20: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	19: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	18: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	17: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	16: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	15: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	14: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	13: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	12: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	11: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	10: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/lib/shopify-cli/command.rb:19:in `call'
	 9: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/lib/shopify-cli/sub_command.rb:13:in `call'
	 8: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/lib/project_types/extension/commands/serve.rb:29:in `call'
	 7: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/lib/shopify-cli/result.rb:173:in `then'
	 6: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/lib/shopify-cli/result.rb:416:in `block in wrap'
	 5: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/lib/project_types/extension/commands/serve.rb:47:in `find_available_port'
	 4: from /Users/bogdan/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/delegate.rb:83:in `method_missing'
	 3: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/lib/project_types/extension/models/specification_handlers/default.rb:46:in `choose_port?'
	 2: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/lib/project_types/extension/models/specification_handlers/default.rb:69:in `argo_runtime'
	 1: from /Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/lib/project_types/extension/models/specification_handlers/default.rb:64:in `renderer_package'
/Users/bogdan/.rvm/gems/ruby-2.7.0/gems/shopify-cli-2.0.2/lib/project_types/extension/models/specification_handlers/default.rb:97:in `argo': undefined method `git_template' for nil:NilClass (NoMethodError)
```

**Comment by pociej** [comment]
exactly same error here.

**Comment by bogdanrn** [comment]
I did a bit of digging into the gem of shopify-cli and i adde this log into `fetch_specifications.rb` 

```
        response = ShopifyCli::PartnersAPI
          .query(context, "fetch_specifications", api_key: api_key)
          .dig("data", "extensionSpecifications")

        logger.info "!!!!!!!!!"
        logger.info response
        logger.info "!!!!!!!!!"
``` 

The log returns the following info: 
```
...
"features"=>{"argo"=>nil}
...
```

From what i understand, this is a response from graphql into partners api. Could it be that issue is something related to our organisation instead of the cli itself?

**Comment by catlee** [comment]
it looks like this is happening for theme app extensions?

currently `shopify extension serve` isn't supported for theme app extensions.

we shouldn't throw this error though! I'll make sure we get a better error message displayed.

**Comment by derekmorin** [comment]
@kevinflo indeed the error message is now "improved", but Shopify doesn't tell us how to make it work, their docs is either wrong or there is a real issue that it seems is ignored by them

**Comment by adamczykjac** [comment]
> Sorry if I wasn't clear above; just to clarify, `shopify extension serve` is currently not supported just for theme app extensions specifically. It should still work for other extension types.

Ok you made that clear, but on the same hand there are these official docs right here (and that's where I came from):
https://shopify.dev/apps/subscriptions/app-extensions/cli-commands#shopify-extension-serve

**Comment by ryangall7** [comment]
Until Shopify provides a clean way to develop theme app extensions it's not worth it to build them. I love the idea behind them but can't do much without a realistic development workflow.
