### ISSUE TITLE
shopify populate products not working

### ISSUE THREAD

**Issue by satelin2002** [Shopify/shopify-cli#1349]
# Issue summary

Write a short description of the issue here ↓
when i run shopify populate products
I get 
✗ Command not allowed with current login. Please check your login details with shopify whoami. You may need to request additional permissions for this action.

 i tried running shopify whoami
and it says Logged into store wonderfulshark.myshopify.com in partner organization Temp

so what is wrong here.

**Comment by satelin2002** [comment]
any updates on this?

**Comment by satelin2002** [comment]
friendly ping :)

**Comment by Teetomania** [comment]
👋@mkevinosullivan, any update on this yet? I have the same issue and have been at it for days.

**Comment by wakamin** [comment]
Confirmed that I have to login as staff user then I can use shopify populate products. 
It should be allowed for store owner as well.

**Comment by jhernandez-c** [comment]
Please refer to https://github.com/Shopify/shopify-cli/issues/1361#issuecomment-879414997 for another workaround if you don't want to create a new staff memeber.

**Comment by jhernandez-c** [comment]
Please refer to https://github.com/Shopify/shopify-cli/issues/1361#issuecomment-879426041 for another workaround if you don't want to create a new staff member.

**Comment by ifat420** [comment]
PS C:\Windows\system32> shopify populate products
This command ran with ID: 13449
Please include this information in any issues/report along with relevant logs
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/api.rb:74:in `block in request': 404 (ShopifyCli::API::APIRequestNotFoundError)
{"errors":"Not Found"}
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/api.rb:86:in `request'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/api.rb:36:in `query'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:136:in `block in fetch_api_version'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:143:in `fetch_api_version'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:117:in `api_client'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:42:in `block in query'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:43:in `query'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api/schema.rb:10:in `get'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api/populate_resource_command.rb:113:in `schema'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api/populate_resource_command.rb:102:in `input_options'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api/populate_resource_command.rb:33:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api/populate_resource_command.rb:17:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/command.rb:19:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/executor.rb:15:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/monorail.rb:32:in `log'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/bin/shopify:33:in `block in <main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.1.0/bin/shopify:32:in `<main>'

**Comment by GuillermoCasanova** [comment]
I'm getting a very similar error above when running 'populate' products as well: 


```

This command ran with ID: 42495
Please include this information in any issues/report along with relevant logs
/usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/api.rb:74:in `block in request': 404 (ShopifyCli::API::APIRequestNotFoundError)
{"errors":"Not Found"}
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/api.rb:86:in `request'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/api.rb:36:in `query'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:136:in `block in fetch_api_version'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:143:in `fetch_api_version'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:117:in `api_client'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:42:in `block in query'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:43:in `query'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api/schema.rb:10:in `get'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api/populate_resource_command.rb:113:in `schema'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api/populate_resource_command.rb:102:in `input_options'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api/populate_resource_command.rb:33:in `call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api/populate_resource_command.rb:17:in `call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/command.rb:19:in `call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/executor.rb:15:in `call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/monorail.rb:20:in `log'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/bin/shopify:33:in `block in <top (required)>'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/bin/shopify:32:in `<top (required)>'
        from /usr/local/bin/shopify:6:in `load'
        from /usr/local/bin/shopify:6:in `<main>'
```

**Comment by 2milesaway** [comment]
> Confirmed that I have to login as staff user then I can use shopify populate products. It should be allowed for store owner as well.

How to login as staff member?
What I can see is to use `shopify login --store=ABC`, how could we specify the staff member id?

**Comment by 2milesaway** [comment]
> Bumping this issue as it still exists. Shouldn't have to login as a staff member if we are logged in as partner account who created the development store. Need a real fix for this issue moving forward.

I think the Shopify tools suck...
I had the same issue, and found a lot of people having the same issue, but no clear and simple solutions, sad.

What I did was,
1) First logout the Shopify Partner via browser.
2) Then on terminal, do `shopify login`, this will open the browser and do the login there.

Then tried `shopify populate products` again, and it worked.
No work related to staff users or whatever at all... 
Tool sucks

**Comment by ElhadiRagabaat** [comment]
✗ Command not allowed with current login. Please check your login details with shopify whoami. You may need to request additional permissions for this action.

**Comment by saricden** [comment]
Bumping issue, as I tried @2milesaway 's approach to no success. Still receiving the above "Command not allowed with current login." message. Please advise, thanks.

**Comment by HauntedSmores** [comment]
This is still happening using a fresh development store through Partners account. Logging in / out of the CLI and dashboards does not seem to help.

**Comment by AndrewNelson951** [comment]
Try this in your store directory:
shopify login --store=YOURSTORENAME
shopify populate products

**Comment by mashkovtsevlx** [comment]
The same is happening to me. The development store was created by the partner organization. I tried logging out (both browser and shopify-cli) and clearing the browser cache. No result

**Comment by crobbo** [comment]
@ecolss answer worked for me, nice one!

**Comment by bivav** [comment]
> # Issue summary
> 
> Write a short description of the issue here ↓ when i run shopify populate products I get ✗ Command not allowed with current login. Please check your login details with shopify whoami. You may need to request additional permissions for this action.
> 
> i tried running shopify whoami and it says Logged into store wonderfulshark.myshopify.com in partner organization Temp
> 
> so what is wrong here.

@satelin2002  @mashkovtsevlx @saricden @ElhadiRagabaat 

Hi all,
A little late to the party but I finally fixed this issue which was giving me a hard time as well.

The reason why many of us could log in via CLI but were unable to populate data was because of the store-specific permission given to members/staff.
You can test this by opening up an incognito browser and trying logging in to dev store `{shop}.myshopify.com/admin`, you'd most probably see `Unable to access {shop name}`

So try this:
1. Log in to the dev store via the partner's account.
2. Click on the top right menu of the dev store and go to "**Your Profile**"
3. Go to "**Users and permissions**"
4. Click on the **Add Staff** section
5. Add any permission you want for that email.
6. Save.
7. Open incognito and try accessing your store with the staff account you just created `{shop}.myshopify.com/admin`
8. If you were able to log in then you can also use **Shopify CLI** to populate data using that staff account

Hope it helps!
