### ISSUE TITLE
`shopify login` command does not account for Organization specificity

### ISSUE THREAD

**Issue by tywayne** [Shopify/shopify-cli#1421]
# Issue summary

I have a Partner account that I develop stores with on my own. I am also a Team Member with full access to stores in a separate Partner Organization (with the same email address as my Partner account).

When using the Shopify CLI, I can successfully login to the alternate Partner account stores, but get an authorization error when attempting to run any commands against that store. (ie, `shopify theme serve`)

## Expected behavior

If I am successfully logged into a store (with `shopify login --store[store_id]`), I should be able authorized to run commands against that store, regardless of which Organization the store is a part of.

## Actual behavior

When I log in to a store in the alternate Partner account, it successfully logs in.

When I run `shopify whoami` I get:
```
Logged into store [correct_store_name] in partner organization [incorrect partner org]
```

Error Message after running `shopify theme push --themeid=************`
<details>
This command ran with ID: 32433
Please include this information in any issues/report along with relevant logs
/opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/api.rb:72:in `block in request': 403 (ShopifyCli::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/api.rb:86:in `request'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:92:in `block in rest_request'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:95:in `rest_request'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/theme/theme.rb:190:in `load_info_from_api'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/theme/theme.rb:81:in `role'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/theme/theme.rb:86:in `live?'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/project_types/theme/commands/push.rb:46:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/sub_command.rb:13:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/command.rb:19:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/executor.rb:15:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/monorail.rb:20:in `log'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/bin/shopify:33:in `block in <top (required)>'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/bin/shopify:32:in `<top (required)>'
	from /opt/homebrew/bin/shopify:6:in `load'
	from /opt/homebrew/bin/shopify:6:in `<main>'
</details>

## Steps to reproduce the problem

1. `shopify login --store=[store]` where store is a store in the Partner Org I am a team member of (not owner of)
1. Use browser to login to Shopify using my email/password (this email/password accesses both my personal Partner account, as well as the Partner account that I am a team member of)
1. `shopify whoami` (will indicate correct store name, but wrong organization name)
1. `shopify theme serve/push/pull` will fail with `Unauthorized Access` error

## Reduced test case
This is not relevant. Steps to reproduce above is the most reduced test case possible.

## Specifications
- App type: N/A
- Operating System: MacOS 11.2
- Shell: ZSH
- Ruby version (ruby -v): 2.7.2

**Comment by tommypepsi** [comment]
I also had this issue at first. What I found is that to correctly log using the shopify CLI you first need to logout from your partner account in the browser and then log using the `shopify login` command. After doing this it got rid of the error for me. Strange thing is that it seems to be working for stores where we are collaborators but not development store. For development stores we need to create a staff account for it to work.

**Comment by DanPete** [comment]
Also having similar issues to this. @tommypepsi solution worked for me. Thanks!
