### ISSUE TITLE
shopify extension push doesn't work with paginate tag

### ISSUE THREAD

**Issue by hnaytroidep** [Shopify/shopify-cli#1447]
# Issue summary

When using `shopify extension push` and the App Block has `{% paginate %} {% endpaginate %}` tags, it throws errors.

## Expected behavior

It should push the extension to Shopify normally.

## Actual behavior

Example: Test with this block in theme-app-extension/blocks/block.liquid

`{%- paginate collection.products by 12 -%}
{%- endpaginate -%}

{% schema %}
  {
  "name": "Paginate block",
  "target": "section",
  "templates": ["collection"],
  "settings": []
  }
{% endschema %}`

Or

`{%- paginate search.results by 12 -%}
{%- endpaginate -%}

{% schema %}
  {
  "name": "Paginate block",
  "target": "section",
  "templates": ["search"],
  "settings": []
  }
{% endschema %}`

<details>shopify extension push
┏━━ Pushing your extension to Shopify ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Pushing code to Shopify…
┃ X An unexpected error occurred on Shopify.
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (30.08s) ━━━
This command ran with ID: 41922
Please include this information in any issues/report along with relevant logs
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/lib/project_types/extension/tasks/update_draft.rb:21:in `call': undefined method `dig' for nil:NilClass (NoMethodError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/lib/shopify-cli/task.rb:7:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/lib/project_types/extension/commands/push.rb:56:in `block in update_draft'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/lib/project_types/extension/commands/push.rb:51:in `with_waiting_text'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/lib/project_types/extension/commands/push.rb:55:in `update_draft'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/lib/project_types/extension/commands/push.rb:15:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/lib/project_types/extension/commands/push.rb:14:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/lib/shopify-cli/sub_command.rb:13:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/lib/shopify-cli/command.rb:19:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/lib/shopify-cli/core/executor.rb:15:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/lib/shopify-cli/core/monorail.rb:20:in `log'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/lib/shopify-cli/core/entry_point.rb:23:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/bin/shopify:33:in `block in <main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.1/bin/shopify:32:in `<main>'
</details>

## Steps to reproduce the problem

1. Run `shopify extension create
cd ./theme-app-extension
shopify extension register`
2. Add file block.liquid in /blocks folder, with example content above
3. Run `shopify extension push`

## Specifications

- App type: Theme App Extension
- Operating System: Windows
- Shell: cmd
- Ruby version (ruby -v): ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]

**Comment by catlee** [comment]
Is this still a problem for you?

**Comment by catlee** [comment]
I can reproduce this now. Looking into a fix.
