### ISSUE TITLE
Moved directory. Shopify Theme Serve Breaks

### ISSUE THREAD

**Issue by ckizer** [Shopify/shopify-cli#1469]
I deleted and started over. Works now. Seems to be something with Git pulling changes from the Shopify version of Dawn and trying to update my copy. Killing ruby and freeing up the port removes some of the errors and get's it working again. Seems to be some bugs with Webfonts though.

**FIXED for now. Kill Ruby Process and try again**

```
This command ran with ID: 57612
Please include this information in any issues/report along with relevant logs
/usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/theme/file.rb:20:in `read': Is a directory @ io_fread - assets/circular paid (Errno::EISDIR)
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/theme/file.rb:20:in `read'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/theme/file.rb:20:in `read'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/theme/file.rb:57:in `checksum'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/theme/syncer.rb:295:in `file_has_changed?'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/theme/syncer.rb:193:in `enqueue'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/theme/syncer.rb:42:in `block in enqueue_updates'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/theme/syncer.rb:42:in `each'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/theme/syncer.rb:42:in `enqueue_updates'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/theme/syncer.rb:152:in `upload_theme!'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/project_types/theme/ui/sync_progress_bar.rb:11:in `public_send'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/project_types/theme/ui/sync_progress_bar.rb:11:in `block in progress'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-ui/lib/cli/ui/progress.rb:34:in `progress'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/project_types/theme/ui/sync_progress_bar.rb:10:in `progress'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/project_types/theme/commands/serve.rb:14:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/theme/dev_server.rb:47:in `block in start'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/theme/dev_server.rb:43:in `start'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/project_types/theme/commands/serve.rb:13:in `call'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/sub_command.rb:13:in `call'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/command.rb:19:in `call'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/core/executor.rb:15:in `call'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/core/monorail.rb:20:in `log'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/lib/shopify-cli/core/entry_point.rb:23:in `call'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/bin/shopify:33:in `block in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/Cellar/shopify-cli/2.2.2/gems/shopify-cli-2.2.2/bin/shopify:32:in `<top (required)>'
	from /usr/local/bin/shopify:6:in `load'
	from /usr/local/bin/shopify:6:in `<main>'
ck@MacBook-Pro Lofty Dawn Theme 2.0 % 

```

**Comment by mkummer225** [comment]
+1 having this issue

Have subdirectories in /assets/..., ie:
/assets/img/.. (.PNG files)
/assets/symbols/Common/... (.svg files)

Works fine when I delete all subdirs in /assets/

CLI 2.3.0

Error:
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/theme/file.rb:23:in `read': Is a directory @ io_fread - assets/img (Errno::EISDIR)
... similar call stack to OP's ...

**Comment by macournoyer** [comment]
I think the root cause might have been the use of subdir under assets. I'll make sure we clarify in the docs that this is not supported.

Let me know if you think there was another issue.
