### ISSUE TITLE
Shopify "create, connect, login" commands crash | This command ran with ID: 10862

### ISSUE THREAD

**Issue by CNFloss** [Shopify/shopify-cli#1546]
# Issue summary

Write a short description of the issue here ↓

Any command I run that makes a connection to shopify just crashes with a vague error 

## Expected behavior

What do you think should happen?

An ngrok tunnel should probably spin up, other scripts run to update credentials, and lastly some sort of success message.

## Actual behavior

What actually happens?

This with the ID varying depending on the command used.

This command ran with ID: 10862
Traceback (most recent call last):
        40: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/bin/shopify:32:in `<main>'
        39: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        38: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/bin/shopify:33:in `block in <main>'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/monorail.rb:32:in `log'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/executor.rb:15:in `call'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/command.rb:25:in `call'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/commands/login.rb:33:in `call'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/identity_auth.rb:65:in `authenticate'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/identity_auth.rb:132:in `request_access_token'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/identity_auth.rb:208:in `post_token_request'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.3.0/lib/shopify-cli/identity_auth.rb:218:in `post_request'
        13: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:1483:in `request'
        12: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:933:in `start'
        11: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:1485:in `block in request'
        10: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:1492:in `request'
         9: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request'
         8: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:1519:in `catch'
         7: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:1528:in `block in transport_request'
         6: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http/response.rb:31:in `read_new'
         5: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http/response.rb:42:in `read_status_line'
         4: from C:/Ruby27-x64/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/net/protocol.rb:210:in `rbuf_fill'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/openssl/buffering.rb:182:in `read_nonblock'
C:/Ruby27-x64/lib/ruby/2.7.0/openssl/buffering.rb:182:in `sysread_nonblock': An existing connection was forcibly closed by the remote host. (Errno::ECONNRESET)

## Steps to reproduce the problem

1. after the CLI install, running any command that tries to connect to shopify does this for me

## Specifications

- App type: Private
- Operating System: Windows 10
- Shell: Powershell (Visual studio codeterminal) 
- Ruby version (ruby -v): ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]

**Comment by CNFloss** [comment]
I was on a public network at the library when I tried this and now on my own home private network it works.  I don't know if that was the fix or something else.
