### ISSUE TITLE
Suddenly getting errors with "shopify theme serve"

### ISSUE THREAD

**Issue by andyaylward** [Shopify/shopify-cli#1551]
# Issue summary

Write a short description of the issue here ↓

I have been using Shopify CLI to create a development theme as I prepare a theme for a client. I was serving the theme and all was well, until I stopped to run `shopify populate products` to add some sample products to the store. After that, I tried running `shopify theme serve` again, but I am now faced with many errors and unable to initiate my development theme.

## Expected behavior

What do you think should happen?

Development theme should be served as normal. I have tried logging out and logging back in multiple times, and restarting my macbook.

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

The error message I receive in iTerm after running shopify theme serve is as follows.

```
This command ran with ID: 73041
Please include this information in any issues/report along with relevant logs
/usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/theme/file.rb:23:in `read': Is a directory @ io_fread - assets/css (Errno::EISDIR)
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/theme/file.rb:23:in `read'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/theme/file.rb:23:in `read'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/theme/file.rb:65:in `checksum'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/theme/syncer.rb:295:in `file_has_changed?'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/theme/syncer.rb:193:in `enqueue'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/theme/syncer.rb:42:in `block in enqueue_updates'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/theme/syncer.rb:42:in `each'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/theme/syncer.rb:42:in `enqueue_updates'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/theme/syncer.rb:152:in `upload_theme!'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/project_types/theme/ui/sync_progress_bar.rb:11:in `public_send'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/project_types/theme/ui/sync_progress_bar.rb:11:in `block in progress'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-ui/lib/cli/ui/progress.rb:34:in `progress'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/project_types/theme/ui/sync_progress_bar.rb:10:in `progress'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/project_types/theme/commands/serve.rb:14:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/theme/dev_server.rb:47:in `block in start'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/theme/dev_server.rb:43:in `start'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/project_types/theme/commands/serve.rb:13:in `call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/sub_command.rb:13:in `call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/command.rb:19:in `call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/core/executor.rb:15:in `call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/core/monorail.rb:32:in `log'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/bin/shopify:33:in `block in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/bin/shopify:32:in `<top (required)>'
	from /usr/local/bin/shopify:6:in `load'
	from /usr/local/bin/shopify:6:in `<main>'
```

I really appreciate any help with this, I am desperate to get my development theme back up and running. Thank you

**Comment by andyaylward** [comment]
> @andyaylward I've had similar errors multiple times, and each time I've resolved by re-updating the homebrew cask for shopify-cli and restarting my computer. Do these steps work for you? Not saying this is a solution, but may help you in the short term.

Thank you for your reply. Would you mind sharing the commands you used in this process? `brew update` returns a line saying homebrew is already up-to-date.

**Comment by evankford** [comment]
Ah, perhaps I should clarify I re-ran the setup steps specified by Shopify.

````` 
brew tap shopify/shopify
brew install themekit
`````

**Comment by evankford** [comment]
@andyaylward Oops! Trying to help, but I'm making it worse. I grabbed the themekit command rather than the Shopify cli ones. This is from the [Shopify-Cli readme.](https://github.com/Shopify/shopify-cli#to-upgrade-shopify-cli)
````` 
brew update
brew upgrade shopify-cli
`````

**Comment by andyaylward** [comment]
> ```
> brew upgrade shopify-cli
> ```

Thanks for clarifying. I am getting a warning relating to my MacOS, but I don't think that is the issue since my development theme has been working fine for over a week until last night. Additionally, I am already using Shopfiy-CLI v2.4.0

```
Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

Warning: shopify/shopify/shopify-cli 2.4.0 already installed
```

**Comment by andyaylward** [comment]
### UPDATE 2

Turns out that having _any_ directory inside of my assets folder was throwing this error when running `shopify theme serve`, even just an empty folder. I was able to fix this by removing the directory, and just moving my scss folder to the themes root, and compiling in assets/styles.css
