### ISSUE TITLE
403 Error - When Using Shopify Theme Pull

### ISSUE THREAD

**Issue by eraynai** [Shopify/shopify-cli#1571]
# Issue summary

Write a short description of the issue here ↓
Getting 403 error (ShopifyCLI::API::APIRequestForbiddenError) after logging into account successfully and using the command shopify theme pull

## Expected behavior

What do you think should happen?

A menu should appear with a selection of a theme to pull from

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

<details>
{"errors":"Unauthorized Access"}
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/api.rb:86:in `request'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/admin_api.rb:95:in `rest_request'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/theme/theme.rb:166:in `all'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/project_types/theme/forms/select.rb:20:in `themes'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/project_types/theme/forms/select.rb:9:in `block in ask'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:188:in `ask_interactive'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:100:in `ask'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/project_types/theme/forms/select.rb:8:in `ask'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/form.rb:13:in `ask'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/project_types/theme/commands/pull.rb:25:in `call'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/sub_command.rb:13:in `call'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/command.rb:19:in `call'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/executor.rb:15:in `call'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/monorail.rb:32:in `log'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/bin/shopify:33:in `block in <top (required)>'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /usr/local/Cellar/shopify-cli/2.5.0/gems/shopify-cli-2.5.0/bin/shopify:32:in `<top (required)>'
        from /usr/local/bin/shopify:6:in `load'
        from /usr/local/bin/shopify:6:in `<main>'
</details>

## Steps to reproduce the problem

1.
1.
1.

## Specifications

- App type:
- Operating System: MacOS 11.6
- Shell: Hyper
- Ruby version (ruby -v): ruby 3.0.2p107

**Comment by ADTC** [comment]
@eraynai why did you close this? I'm getting the same problem, but only in one particular store. I have the permission to Customize and use Code Editor online.

**Comment by ADTC** [comment]
Here's what worked for me:

1. Run `shopify logout`.
2. Open your primary browser and log out of all Shopify accounts.
    - You'll have to switch between each account and log them out one by one.
3. Open the browser settings and remove all cookies and site data for the search string `shopify`.
    - Alternatively you can also clear all cookies and cache, but this will log you out of every website.
4. Run `shopify login` (optionally with `--store=STORE`). Log in to your account.
5. Try running your theme commands now.

**Comment by willryanuk** [comment]
In my case, it was because my user account did not have enough permissions...

Under _Settings > Users and Permissions >_ make sure you have the permission for **Themes** ticked.
