### ISSUE TITLE
[URGENT] 500 Internal Server Error when attempting to push, serve, etc.

### ISSUE THREAD

**Issue by ADTC** [Shopify/shopify-cli#1598]
# Issue summary

Getting 500 Internal Server Error when attempting to push changed theme files. **Unable to use Shopify CLI to work on the theme.**

## Expected behavior

Pushes the theme files.

## Actual behavior

500 Internal Server Error:

<details>

```
> shopify logout
Successfully logged out of your account

> shopify login --store=mystore.myshopify.com
Initializing...
X An unexpected error occurred on Shopify.
Logged into store mystore.myshopify.com as staff (no partner organizations available for this login)

> shopify theme push -i 12xxxxxxxx19
This command ran with ID: 4xxx3
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/bin/shopify:32:in `<main>'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/bin/shopify:33:in `block in <main>'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/monorail.rb:32:in `log'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/executor.rb:15:in `call'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/command.rb:19:in `call'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/sub_command.rb:13:in `call'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/project_types/theme/commands/push.rb:50:in `call'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/theme/theme.rb:86:in `live?'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/theme/theme.rb:81:in `role'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/theme/theme.rb:190:in `load_info_from_api'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/admin_api.rb:95:in `rest_request'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/api.rb:86:in `request'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/api.rb:80:in `block in request': 500 (ShopifyCLI::API::APIRequestServerError)
{"errors":"Internal Server Error"}
```
</details>

## Steps to reproduce the problem

1. Login with Shopify CLI.
1. Push changes to theme files.

## Specifications

- App type: CLI 2.5.0
- Operating System: Windows 10
- Shell: Command Prompt
- Ruby version (ruby -v): ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]

**Comment by rscaduto** [comment]
This doesn't seem to be restricted to pushing changes. I'm getting the same error from just theme serve.

**Comment by mojosef** [comment]
Same issue here with `theme serve`. Seems to be related to the outages as shown by @ADTC.
