### ISSUE TITLE
shopify node create - An unexpected error occurred

### ISSUE THREAD

**Issue by remotetech** [Shopify/shopify-cli#1660]
# Issue summary
Building new node app as normal but now I'm getting an unexpected error occurred when running the command shopify node create ↓

## Expected behavior
I normally creates the app and then I would be able to issue the shopify node serve command.

## Actual behavior
Crashes shortly after running the shopify node create command

PS C:\> shopify node create
? App name
> tech-app24
? What type of app are you building? (Navigate up with 'k' and down with 'j', press Ente? What type of app are you building? (You chose: Public: An app built for a wide merchant audience.)
X An unexpected error occured.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.
** [Bugsnag] 2021-10-20 03:44:10 -0700: Unable to send information to Bugsnag (https://notify.bugsnag.com), #<OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello>
** [Bugsnag] 2021-10-20 03:44:10 -0700: ["C:/Ruby30-x64/lib/ruby/3.0.0/net/protocol.rb:46:in `connect_nonblock'", "C:/Ruby30-x64/lib/ruby/3.0.0/net/protocol.rb:46:in `ssl_socket_connect'", "C:/Ruby30-x64/lib/ruby/3.0.0/net/http.rb:1038:in `connect'", "C:/Ruby30-x64/lib/ruby/3.0.0/net/http.rb:970:in `do_start'", "C:/Ruby30-x64/lib/ruby/3.0.0/net/http.rb:959:in `start'", "C:/Ruby30-x64/lib/ruby/3.0.0/net/http.rb:1512:in `request'", "C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bugsnag-6.24.0/lib/bugsnag/delivery/synchronous.rb:51:in `request'", "C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bugsnag-6.24.0/lib/bugsnag/delivery/synchronous.rb:12:in `deliver'", "C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bugsnag-6.24.0/lib/bugsnag/delivery/thread_queue.rb:38:in `block in serialize_and_deliver'", "C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bugsnag-6.24.0/lib/bugsnag/delivery/thread_queue.rb:55:in `block (2 levels) in start_once!'"]

## Steps to reproduce the problem
1. shopify node create
1. enter app name
1. select type of app you are building (public)

![shopify-node-create-error](https://user-images.githubusercontent.com/9343832/138079845-a02b48a8-8181-4e4b-b6fc-3972d53191c8.png)

## Specifications
- App type: Shopify Node App
- Operating System: Windows 10
- Shell: Windows Power Shell
- Ruby version (ruby -v): ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]

**Comment by remotetech** [comment]
Uninstalled Everything :)
node js, ruby , etc.
removed anything that I installed to create the app project.
Then I re-installed and now I'm not getting the errors anymore. 
Regards, remotetech
