### ISSUE TITLE
Shopify CLI Error when pushing a Theme App Extension with more than 25 asset files

### ISSUE THREAD

**Issue by supercart** [Shopify/shopify-cli#1698]
# Issue summary

Write a short description of the issue here ↓

When pushing a theme-app-extension with more than 25 asset files ( CSS / JS ), it gives an error. 
All files are under 9kb (minified and compressed) 

The theme-app-extension is using lazy component loading, and not all files are used at the same time. 
They are loaded dynamically based on the user behavior.

It looks like all files are published successfully, but the CLI throws an error message.

## Expected behavior

What do you think should happen?

The theme app extension should publish successfully. There should be no errors in the Shopify CLI.

## Actual behavior

What actually happens?

```
┏━━ Pushing your extension to Shopify ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Pushing code to Shopify…
┃ ✗ An unexpected error occurred on Shopify.
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (116.8s) ━━

✗ An unexpected error occured.
        To submit an issue include the stack trace.

/usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/lib/project_types/extension/tasks/update_draft.rb:21:in `call': undefined method `dig' for nil:NilClass (NoMethodError)
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/lib/shopify_cli/task.rb:7:in `call'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/lib/project_types/extension/commands/push.rb:56:in `block in update_draft'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/lib/project_types/extension/commands/push.rb:51:in `with_waiting_text'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/lib/project_types/extension/commands/push.rb:55:in `update_draft'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/lib/project_types/extension/commands/push.rb:15:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/lib/project_types/extension/commands/push.rb:14:in `call'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/lib/shopify_cli/sub_command.rb:13:in `call'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/lib/shopify_cli/command.rb:19:in `call'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/lib/shopify_cli/core/executor.rb:15:in `call'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/lib/shopify_cli/core/monorail.rb:20:in `log'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/lib/shopify_cli/core/entry_point.rb:23:in `call'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/bin/shopify:37:in `block (2 levels) in <top (required)>'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/bin/shopify:36:in `block in <top (required)>'
        from /usr/local/Cellar/shopify-cli/2.6.3/gems/shopify-cli-2.6.3/bin/shopify:47:in `<top (required)>'
        from /usr/local/bin/shopify:6:in `load'
        from /usr/local/bin/shopify:6:in `<main>'
```

## Steps to reproduce the problem

1. Create a theme app extension with 1 liquid block 
1. Add 20 - 30 JS files 
1. Add 1 css file
1. run shopify extension push 

## Specifications

- App type: Theme App Extension / Ruby on Rails
- Operating System: Mac Os X - 10.15.3
- Shell:
- Ruby version (ruby -v): ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin19]

**Comment by sagar-ranglani** [comment]
I got this error with assets fewer than 25 (about 22) so I guess there is no hard limit for this.
This is kinda a blocker for us as we need to store a good number of small images.

Also, it seems that it is not possible to create a folder inside the assets folder, please correct me if I am wrong. I do want to keep the assets (images, icons, CSS and JS) well organized inside the assets folder.

**Comment by supercart** [comment]
Indeed, the first time when I got this error, I had exactly 22 files.

Also, It looks like the error from `update_draft.rb:21` was submitted on this issue as well.
https://github.com/Shopify/shopify-cli/issues/1447

**Comment by sagar-ranglani** [comment]
Any updates on this?

**Comment by smehtaAA** [comment]
+1

**Comment by zakariamofaddel** [comment]
+1

**Comment by andrewbien** [comment]
I also struggle with that issue. I hope the Shopify CLI team will fix it soon, it's very important for our app :(

**Comment by zakariamofaddel** [comment]
> I also struggle with that issue. I hope the Shopify CLI team will fix it soon, it's very important for our app :(

Just FYI, know that the files are actually getting pushed, even if you get the error. I developed my full application while getting that error.

**Comment by catlee** [comment]
Has there been any improvement since about 13:00 UTC today?
