### ISSUE TITLE
The `theme serve` command fails with the `--host` property

### ISSUE THREAD

**Issue by karreiro** [Shopify/shopify-cli#1765]
# Issue summary

Users cannot use the `--host` property.

## Expected behavior

When users try to use the `--host` property, the `theme serve` must successfully bind this host.

## Actual behavior

When users try to use the `--host` property, the `theme serve` command fails.

## Steps to reproduce the problem

Run:

```
shopify theme serve --host=0.0.0.0
```

## Stacktrace

```
Traceback (most recent call last):
	24: from /Users/karreiro/src/github.com/Shopify/shopify-cli/bin/shopify:47:in `<main>'
	23: from /Users/karreiro/src/github.com/Shopify/shopify-cli/bin/shopify:36:in `block in <main>'
	22: from /Users/karreiro/src/github.com/Shopify/shopify-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	21: from /Users/karreiro/src/github.com/Shopify/shopify-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	20: from /Users/karreiro/src/github.com/Shopify/shopify-cli/bin/shopify:37:in `block (2 levels) in <main>'
	19: from /Users/karreiro/src/github.com/Shopify/shopify-cli/lib/shopify_cli/core/entry_point.rb:23:in `call'
	18: from /Users/karreiro/src/github.com/Shopify/shopify-cli/lib/shopify_cli/core/monorail.rb:30:in `log'
	17: from /Users/karreiro/src/github.com/Shopify/shopify-cli/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
	16: from /Users/karreiro/src/github.com/Shopify/shopify-cli/lib/shopify_cli/core/executor.rb:15:in `call'
	15: from /Users/karreiro/src/github.com/Shopify/shopify-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	14: from /Users/karreiro/src/github.com/Shopify/shopify-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	13: from /Users/karreiro/src/github.com/Shopify/shopify-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	12: from /Users/karreiro/src/github.com/Shopify/shopify-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	11: from /Users/karreiro/src/github.com/Shopify/shopify-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	10: from /Users/karreiro/src/github.com/Shopify/shopify-cli/lib/shopify_cli/core/executor.rb:16:in `block in call'
	 9: from /Users/karreiro/src/github.com/Shopify/shopify-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	 8: from /Users/karreiro/src/github.com/Shopify/shopify-cli/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	 7: from /Users/karreiro/src/github.com/Shopify/shopify-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	 6: from /Users/karreiro/src/github.com/Shopify/shopify-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	 5: from /Users/karreiro/src/github.com/Shopify/shopify-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	 4: from /Users/karreiro/src/github.com/Shopify/shopify-cli/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
	 3: from /Users/karreiro/src/github.com/Shopify/shopify-cli/lib/shopify_cli/command.rb:24:in `call'
	 2: from /Users/karreiro/src/github.com/Shopify/shopify-cli/lib/shopify_cli/command/sub_command.rb:14:in `call'
	 1: from /Users/karreiro/src/github.com/Shopify/shopify-cli/lib/project_types/theme/commands/serve.rb:18:in `call'
/Users/karreiro/src/github.com/Shopify/shopify-cli/lib/shopify_cli/theme/dev_server.rb:27:in `start': unknown keyword: :host (ArgumentError)

```

**Comment by karreiro** [comment]
#1766
