### ISSUE TITLE
Cannot theme pull/push

### ISSUE THREAD

**Issue by kinngh** [Shopify/shopify-cli#1772]
# Issue summary

Cannot run `shopify theme pull` or `shopify theme push` on certain stores even after having the right access / reauth from the store.

## Expected behavior

What do you think should happen?
`shopify theme pull` to show a list of themes and download theme locally.

## Actual behavior

What actually happens?

<details>
Terminal throws
```
✗ An unexpected error occured.
	To submit an issue include the stack trace.
	To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.
```
</details>

## Steps to reproduce the problem

1. Login to store using the Shopify-cli
2. Run `shopify theme pull`

## Stacktrace

```
/usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/api.rb:74:in `block in request': 403 (ShopifyCLI::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/api.rb:89:in `request'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/admin_api.rb:95:in `rest_request'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/theme/theme.rb:166:in `all'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/project_types/theme/forms/select.rb:20:in `themes'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/project_types/theme/forms/select.rb:9:in `block in ask'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:188:in `ask_interactive'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:100:in `ask'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/project_types/theme/forms/select.rb:8:in `ask'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/form.rb:13:in `ask'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/project_types/theme/commands/pull.rb:25:in `call'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/command/sub_command.rb:14:in `call'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/command.rb:24:in `call'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/core/executor.rb:16:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/core/executor.rb:15:in `call'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/core/monorail.rb:30:in `log'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/core/entry_point.rb:23:in `call'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/bin/shopify:37:in `block (2 levels) in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/bin/shopify:36:in `block in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/bin/shopify:47:in `<top (required)>'
	from /usr/local/bin/shopify:6:in `load'
	from /usr/local/bin/shopify:6:in `<main>'
```

## Specifications

- App type: Theme / shopify-cli
- Operating System: macOS 12.0.1
- Shell: ZSH
- Ruby version (ruby -v): 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

**Comment by kinngh** [comment]
Additional information:

I've been using the hacks of creating a staff account in my org to ensure I can login, though not really sure why things don't work straight up with a simple auth.
