### ISSUE TITLE
shopify theme serve error: Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by KimKJDesigns** [Shopify/shopify-cli#1779]
# Issue summary

Running `shopify theme serve` throws an error.

## Expected behavior

Theme should be accessible through the browser.

## Actual behavior

Error is thrown immediately.

## Steps to reproduce the problem

1. Follow steps outlined in documentation [Official Shopify Site](https://shopify.dev/themes/getting-started/create)
2. Get to step 4 for previewing the theme

## Stacktrace
```
/usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/json/common.rb:312:in `generate': "\\xE2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
from /usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/json/common.rb:312:in `generate'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/theme/theme.rb:108:in `create'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/theme/development_theme.rb:37:in `ensure_exists!'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/theme/dev_server.rb:41:in `start'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/project_types/theme/commands/serve.rb:18:in `call'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/command/sub_command.rb:14:in `call'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/command.rb:24:in `call'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/core/executor.rb:16:in `block in call'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/core/executor.rb:15:in `call'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/core/monorail.rb:30:in `log'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/lib/shopify_cli/core/entry_point.rb:23:in `call'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/bin/shopify:37:in `block (2 levels) in <top (required)>'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/bin/shopify:36:in `block in <top (required)>'
from /usr/local/Cellar/shopify-cli/2.7.1/gems/shopify-cli-2.7.1/bin/shopify:47:in `<top (required)>'
from /usr/local/bin/shopify:6:in `load'
from /usr/local/bin/shopify:6:in `<main>'
```

## Specifications

- App type: shopify-cli / theme
- Operating System: MacOS Big Sur 11.6.1
- Shell: zshrc
- Ruby version (ruby -v): ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

**Comment by KimKJDesigns** [comment]
The problem stems from my hostname containing a character (comma) that couldn't be converted to UTF-8.

It was resolved using the following steps:
1. `sudo scutil --get HostName`
2. `sudo scutil --get ComputerName`
3. Check if HostName and ComputerName contains an illegal character
4. `sudo scutil --set HostName "{new name}"`
5. `sudo scutil --set ComputerName "{new name}"`
6. `shopify logout`
7. `shopify login`
8. `shopify switch` <- to select the store you're connecting to
9. `shopify theme serve`

The reason I changed my ComputerName too is just continuity.

**Comment by ADTC** [comment]
@karreiro I'm getting this on a `theme pull` action and because of this, I can't download some of the `.map` files:

![image](https://user-images.githubusercontent.com/6047296/161566464-c88dad05-9591-4f21-80de-106fe075c65c.png)

Do you have any resolution for this? Why is there a conversion from `ASCII-8BIT` to `UTF-8`? What is happening there?

**Comment by ADTC** [comment]
@karreiro the OS is Windows 10 x64.

```
Processor	Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz   2.00 GHz
Installed RAM	16.0 GB
System type	64-bit operating system, x64-based processor
Edition		Windows 10 Home Single Language
Version		20H2
Installed on	‎7/‎17/‎2020
OS build	19042.985
Experience	Windows Feature Experience Pack 120.2212.2020.0
```

Here are some files (I had to download the theme via admin to get them, as the CLI downloads them as zero byte files due to the encoding error.)

[Download "Failing map files.zip" (883 KB)](https://github.com/Shopify/shopify-cli/files/8442407/Failing.map.files.zip)

**Comment by ADTC** [comment]
@karreiro I hope those file were helpful for the investigation :)

**Comment by ADTC** [comment]
@karreiro will there be any fix for this? Could you at least make Shopify CLI just write out the original file if some sort of required "conversion" has failed? (Instead of outputting an empty zero-byte file.)
