### ISSUE TITLE
Errno::EACCES: Permission denied - "C:/Users/Rasmus/AppData/Local/shopify/ngrok" http -inspect=false -log=stdout -log-level=debug 8081

### ISSUE THREAD

**Issue by rmoerch** [Shopify/shopify-cli#1792]
# Issue summary

Write a short description of the issue here ↓

Getting an unexpected error when trying to use command "shopify app serve"

## Expected behavior

What do you think should happen?

Should start a local development server according to this tutorial: https://shopify.dev/apps/getting-started/create

## Actual behavior

What actually happens?

I'm getting an unexpected error. 

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. Navigate to project directory
1. Run "shopify app serve"
1. Error occurs

## Stacktrace

C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.7.1/lib/shopify_cli/process_supervision.rb:82:in `spawn'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.7.1/lib/shopify_cli/process_supervision.rb:82:in `start'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.7.1/lib/shopify_cli/tunnel.rb:198:in `start_ngrok'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.7.1/lib/shopify_cli/tunnel.rb:69:in `start'
C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `start'

## Specifications

- App type: Custom
- Operating System: Win10
- Shell: Ruby command Prompt
- Ruby version (ruby -v): 2.7.4p191

**Comment by rmoerch** [comment]
@jhaastrup  I removed all components from my pc and redid the entire thing. However, I still encountered an ngrok issue. The ngrok.exe could not be located in the supposed destination. I made sure I had the ngrok.exe file in that destination and the zipped version as well, which I then unzipped into a folder named ngrok. Then it worked perfectly.

**Comment by umar9871** [comment]
facing same issue please let me know if someone get solution of this

(Errno::EACCES)

**Comment by jhaastrup** [comment]
@umar9871 I have been able to fix the issue. 
I think is just a hack to make it work. 

in your C:/Users/..../AppData/Local/shopify/ create a folder and name it ngrok and then add your ngrok.exe there
then you will have something like ...Local/shopify/ngrok/ngrok.exe 
then also have Local/shopify/ngrok.exe 

so your ....Local/shopify folder will look like this 

>ngrok>ngrok.exe 
>ngrok.exe 
>.db.pstore 

I hope this helps you.
