### ISSUE TITLE
SocketError: Failed to open TCP connection to partners.shopify.com:443 (getaddrinfo: nodename nor servname provided, or not known)

### ISSUE THREAD

**Issue by xbt14** [Shopify/shopify-cli#1822]
# Issue summary

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Stacktrace

/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/net/http.rb:987:in `initialize'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/net/http.rb:987:in `open'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/net/http.rb:987:in `block in connect'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/timeout.rb:107:in `timeout'

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by juliazdz** [comment]
I have a problem with tcp connection, when do pull, server or push (and shopify-cli work is too slow):
ERROR  » update config/settings_data.json: Failed to open TCP connection to myshopify.com:443 (getaddrinfo: Temporary failure in name resolution) 
or 
ERROR  » update templates/page.contact.liquid: Failed to open TCP connection to myshopify.com:443 (getaddrinfo: Temporary failure in name resolution).

Ruby version: 2.7.0p0
Shopify-cli version: 2.15.2
Operating System: Ubuntu 20.04.4 LTS

What could be the problem?

**Comment by IrisLiu001** [comment]
Did you resolve this? I met the same issue as you got:
"#<SocketError: Failed to open TCP connection to .goat.com:443 (getaddrinfo: nodename nor servname provided, or not known)>"
"Failed to open TCP connection to .goat.com:443 (getaddrinfo: nodename nor servname provided, or not known)"
