### ISSUE TITLE
ShopifyCLI::Tunnel::NgrokError: The authtoken you specified does not look like a proper ngrok tunnel authtoken.\nYour authtoken: 8080\nInstructions to install your authtoken are on your ngrok dashboard:\nhttps://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_105\r\n

### ISSUE THREAD

**Issue by Rahulraikwar000** [Shopify/shopify-cli#1827]
# Issue summary

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Stacktrace

/var/lib/gems/2.7.0/gems/shopify-cli-2.7.2/lib/shopify_cli/tunnel.rb:182:in `rescue in fetch_url'
/var/lib/gems/2.7.0/gems/shopify-cli-2.7.2/lib/shopify_cli/tunnel.rb:178:in `fetch_url'
/var/lib/gems/2.7.0/gems/shopify-cli-2.7.2/lib/shopify_cli/tunnel.rb:197:in `start_ngrok'
/var/lib/gems/2.7.0/gems/shopify-cli-2.7.2/lib/shopify_cli/tunnel.rb:69:in `start'
/usr/lib/ruby/2.7.0/forwardable.rb:235:in `start'

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by Rahulraikwar000** [comment]
ngrok tunnel stop
