### ISSUE TITLE
Errno::ENOENT: No such file or directory - git

### ISSUE THREAD

**Issue by bilal7446** [Shopify/shopify-cli#1904]
# Issue summary

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?
im getting this error when creating new shopify app in php 

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Stacktrace

C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `spawn'
C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:101:in `popen3'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.8.0/lib/shopify_cli/git.rb:169:in `block in clone_progress'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.8.0/vendor/deps/cli-ui/lib/cli/ui/progress.rb:34:in `progress'

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by bilal7446** [comment]
issue was i didnt install git.
