### ISSUE TITLE
RuntimeError: Could not determine OS from platform x64-mingw-ucrt

### ISSUE THREAD

**Issue by avinashseth** [Shopify/shopify-cli#1923]
# Issue summary

Installed shopify cli, trying to run shopify login, getting following error!
## Expected behavior

What do you think should happen?

It should login!

## Actual behavior

What actually happens?

After installing shopify-cli gem, I created folder and there I execute shopify login, getting following error!

![image](https://user-images.githubusercontent.com/4149253/149354991-b65e15b4-6515-4eb6-a76b-407727a04f81.png)

## Steps to reproduce the problem

1. run shopify login

## Stacktrace

C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:181:in `os'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:211:in `resolve_path'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:126:in `system'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/lib/shopify_cli/context.rb:438:in `system'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/lib/shopify_cli/context.rb:331:in `open_browser_url!'

## Specifications

- Operating System: Windows 11 64 bit
- Shell: Don't know
- Ruby version (ruby -v): ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x64-mingw-ucrt]

**Comment by jayantasamaddar** [comment]
The CLI is super buggy. It's an absolute miracle it's working for some.
----------------------------------------------------------------------------
Keep getting the same error as OP, when using `shopify login`

- `shopify login --store=<storename>` throws same error but then,

- `shopify store all` shows **You're currently logged into xxxx.myshopify.com**

Weird. So I proceed to,

-  `shopify node create` and it throws a **"Command not found"** error. 
 
-  I confirm using `shopify version` that I am using the latest version 2.8.0

- Next I use `shopify app create node` to try a variation of the code and this time the error is different -
**Please ensure you've logged in with shopify login and try again**

I just confirm again with `shopify store` all that - **You're currently logged into xxxx.myshopify.com**

What is this bipolar behaviour...I am clueless how to fix this.

I checked system requirements, installed Linux Subsystem for Windows and Ubuntu and tried to run it on Ubuntu. Tried running on VS Code. Tried running on Powershell. Tried running on Command Prompt. Please tell me what to do.

**Comment by jayantasamaddar** [comment]
Just an update.  Since I had Linux Subsystem and Ubuntu installed, I tried to do it the Linux way on Windows 10 and got it to work on WSL. So it's working on Windows now, but not how I intended and with Linux you have limitations. I will still wait for the Windows solution, because this seems to be a Windows specific problem. I want to use VSCode while working.

For anyone curious to know, here's  what I did.

**Installed** 
[Windows Subsystem for Linux](https://docs.microsoft.com/windows/wsl/install-win10)
[Ubuntu VM](https://www.microsoft.com/en-in/p/ubuntu)

I followed this tutorial: [How To Install Shopify CLI for windows 10, mac, ubuntu](https://www.youtube.com/watch?v=Jh_Y504t1L8)

- Had to install the following dependencies which are nowhere mentioned in the shopify documentation - 

`sudo apt update`
`sudo apt-get update`
`sudo apt install npm nodejs` (you need both, the tutorial missed this)
`sudo apt-get install ruby-full`
`sudo apt-get install build-essential`
`sudo apt-get install bison openssl curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libxml2-dev autoconf libc6-dev ncurses-dev automake libtool`
`sudo gem install shopify-cli`

- `shopify login` provided a link...on copy pasting to browser authenticated to partner store. Showed as logged in.

Everything smooth after that. Drawback is that Linux only has root directory, so now no way to use another drive.

Waiting for the Windows fix. I dislike working in the terminal.

**Comment by jayantasamaddar** [comment]
Here's the full error.

> D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:181:in `os': Could not determine 
> OS from platform x64-mingw-ucrt (RuntimeError)
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:211:in `resolve_path'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:126:in `system'     
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/lib/shopify_cli/context.rb:438:in `system'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/lib/shopify_cli/context.rb:331:in `open_browser_url!'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/lib/shopify_cli/identity_auth.rb:136:in `open_browser_authentication'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/lib/shopify_cli/identity_auth.rb:132:in `initiate_authentication'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/lib/shopify_cli/identity_auth.rb:61:in `authenticate'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/lib/shopify_cli/commands/login.rb:33:in `call'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/lib/shopify_cli/command.rb:30:in `call'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'       
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/lib/shopify_cli/core/executor.rb:16:in `block in call'        
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'     
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'     
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'        from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/lib/shopify_cli/core/executor.rb:15:in `call'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'     
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/lib/shopify_cli/core/monorail.rb:30:in `log'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/bin/shopify:37:in `block (2 levels) in <top (required)>'      
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call' 
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/bin/shopify:36:in `block in <top (required)>'
>         from D:/Program Files/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.8.0/bin/shopify:47:in `<top (required)>'
>         from D:/Program Files/Ruby31-x64/bin/shopify:25:in `load'
>         from D:/Program Files/Ruby31-x64/bin/shopify:25:in `<main>'

**Comment by jayantasamaddar** [comment]
`Fetching: nokogiri-1.13.1-x86_64-linux.gem (100%) ERROR: While executing gem ... (Gem::RemoteFetcher::FetchError) bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.1-x64-unknown.gemspec.rz)`

Looks like you have to reattempt. 403 gateway error forbidden means forbidden. Start wsl as administrator and run the sudo apt installs again....maybe that will install correctly.

**Comment by avinashseth** [comment]
@jayantasamaddar run the wsl as administrator but no change! Cannot install linux just for shopify cli :( Which windows version you are using? I'm using windows 11, I hope that is not a problem?

**Comment by nzmitch** [comment]
Try:

gem install shopify-cli -v 2.8.0
Ruby+Devkit 3.0.3-1 (x64)
![150640460-50d26853-5d17-436f-a0bf-76a6b002c2a5](https://user-images.githubusercontent.com/33976247/150699989-3ed207fa-eb83-4c3e-bee8-ef0efb5bfeda.jpg)

Fixed for me!

**Comment by avinashseth** [comment]
@nzmitch your solution worked 😄 thanks!

**Comment by tylertyssedal** [comment]
@avinashseth I was having the same issue. I tried it with 2.8 and it didn't work properly. 

Uninstalled 2.8-3.1 and installed Ruby+Devkit 2.7.X (x64), reinstalled the shopify-cli, and now it is working.

**Comment by travislrogers** [comment]
Thank you @tylertyssedal, that solved the issue for me. I was running the latest version of Ruby (3.1) on Windows. Uninstalling and reinstalling 2.7.5 + Devkit worked!

**Comment by gonzaloriestra** [comment]
This should be fixed in [version 2.10.2](https://github.com/Shopify/shopify-cli/releases/tag/v2.10.2). Thanks for the patience!

**Comment by pinguluk** [comment]
> This should be fixed in [version 2.10.2](https://github.com/Shopify/shopify-cli/releases/tag/v2.10.2). Thanks for the patience!

```
C:/Ruby30-x64/lib/ruby/3.0.0/socket.rb:201:in `bind': Permission denied - bind(2) for 0.0.0.0:3456 (Errno::EACCES)
        from C:/Ruby30-x64/lib/ruby/3.0.0/socket.rb:201:in `listen'
        from C:/Ruby30-x64/lib/ruby/3.0.0/socket.rb:765:in `block in tcp_server_sockets'
        from C:/Ruby30-x64/lib/ruby/3.0.0/socket.rb:227:in `each'
        from C:/Ruby30-x64/lib/ruby/3.0.0/socket.rb:227:in `foreach'
        from C:/Ruby30-x64/lib/ruby/3.0.0/socket.rb:763:in `tcp_server_sockets'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.10.2/vendor/deps/webrick/lib/webrick/utils.rb:60:in `create_listeners'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.10.2/vendor/deps/webrick/lib/webrick/server.rb:130:in `listen'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.10.2/vendor/deps/webrick/lib/webrick/server.rb:111:in `initialize'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.10.2/vendor/deps/webrick/lib/webrick/httpserver.rb:47:in `initialize'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.10.2/lib/shopify_cli/identity_auth.rb:103:in `new'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.10.2/lib/shopify_cli/identity_auth.rb:103:in `server'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.10.2/lib/shopify_cli/identity_auth.rb:121:in `block in initiate_authentication'
```
