### ISSUE TITLE
Cannot login as user on store on WIndows

### ISSUE THREAD

**Issue by lesterdefreitas** [Shopify/shopify-cli#1944]
# Issue summary

I'm having issues logging in to a store that I have a user account on with themes access. Previously I had no issues at all.

## Expected behavior

I should be logged in and able to run theme commands.

## Actual behavior

What actually happens?

This is the error that comes back:

```
<details>
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ X Invalid store provided (dev-nexgrill.myshopify.com). Please make sure that the store belongs to your partner organization, and provide the store in the following format: my-store.myshopify.com
┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
</details>
```

The store URL is definitely valid. We keep the shopify login command with the store url stored in the readme file in our theme repos, and I am copying and pasting what I have always used.

The store does not belong to our partner organization, but this was never a problem before. We are using a direct user login that has access to themes. Or has something weird changed in this regard now?

## Steps to reproduce the problem

1. Find a live store that you have a user access on with themes access (no partner account login)
2. Run `shopify login --store=STORE_URL_HERE

## Specifications

- App type:
- Operating System: Windows
- Shell: PowerShell
- Ruby version: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]

**Comment by greimers** [comment]
This is not specific to Windows. We have the same issue on macOS.
It seems that this is a bug introduced in v2.9.0. 
When we downgraded to 2.8 it worked again.

**Feature Request:**
Please make it possible to downgrade to previous version using homebrew on macOS. I had to use the Ruby Gem installer to downgrade, which was quite a pain. (`brew install shopify-cli@2.8` will give errors)

**Comment by ettoredn** [comment]
Same on my end, login into any store of a Shopify Plus organization is not working anymore when using a partner's account. I even have store owner access on my client organization's store.

**Comment by lesterdefreitas** [comment]
> Same on my end, login into any store of a Shopify Plus organization is not working anymore when using a partner's account. I even have store owner access on my client organization's store.

@ettoredn Ah interesting detail thank you! The store we are battling with also happens to be on Plus. When we try on other stores that are not on Plus, but that we also only have direct user login access to, we don't run into the issue. I wonder if it's something to do with cli or with a change to security policies on plus?

**Comment by ettoredn** [comment]
My wild guess is that it has to do with security policies on their backend. I already contacted Plus support yesterday (outside of US business hours) but didn't get an answer yet.

**Comment by DanPete** [comment]
> Feature Request:
Please make it possible to downgrade to previous version using homebrew on macOS. I had to use the Ruby Gem installer to downgrade, which was quite a pain. (brew install shopify-cli@2.8 will give errors)

Also having issues with `shopify login` since updating to 2.9. Would be great to have an easy way to downgrade.

I have had some success doing `shopify logout` and trying to login again.

**Comment by ettoredn** [comment]
@andrewhassan ?

**Comment by KaichenWang** [comment]
I've run into the same issue with `v2.9.0`. Shopify's currently looking into the root cause.

A temporary workaround (as already stated above) would be to revert to `v2.8.0`:

```
gem install shopify-cli -v 2.8.0
```

**Comment by hannachen** [comment]
Hello, the latest update to the Shopify CLI addresses a bug which appears to allow you to log into any store (but does not allow you to take actions in stores you don't have access to).

Those impacted by this fix might be a group of accounts that **uses the same email for both merchant store and partners account**.

Recommendations:
- Change your partner organization email to be different from your merchant/collaborator account
- Change your collaborator account email address to be different from your partner organization account

**Comment by ettoredn** [comment]
@hannachen I changed the email on my partner account so that it differs from the one used on my client's store and now **it **works**. However, the CLI gently suggests me to create a partner account with the same email:

```
error: Your account was not found. Please sign up at https://partners.shopify.com/signup
For authentication issues, run shopify logout to clear invalid credentials
Logged into store <redacted>.myshopify.com as staff (no partner organizations available for this login)
```

Kinda funny.

**Comment by amnkhan** [comment]
I am new to using Shopify CLI, Just installed it on my WINDOWS 10 machine. 

When I use the command `shopify login` 

It takes me to the login page. But when I click login it's showing `{"code":"MethodNotAllowed","message":"GET is not allowed"}` 

Is there anything I am missing?

**Comment by lesterdefreitas** [comment]
> Hello, the latest update to the Shopify CLI addresses a bug which appears to allow you to log into any store (but does not allow you to take actions in stores you don't have access to).
> 
> Those impacted by this fix might be a group of accounts that **uses the same email for both merchant store and partners account**.
> 
> Recommendations:
> 
> * Change your partner organization email to be different from your merchant/collaborator account
> * Change your collaborator account email address to be different from your partner organization account

@hannachen does this mean that the current 'issue' is actually expected functionality? I am a little unsure of how this addresses the problem though. In the original issue report we are referring to a store that we do not have collaborator access to. We only have direct user access, and the user does have the themes permission. Previously we had no trouble logging into this account on shopify-cli, but since 2.9.0 we get the error shown in the issue report description.

Is this expected behaviour? Does shopify-cli now require that we have a collaborator account to log in to any stores?

**Comment by hannachen** [comment]
> @hannachen I changed the email on my partner account so that it differs from the one used on my client's store and now it works. However, the CLI gently suggests me to create a partner account with the same email:
> 
> ```
> error: Your account was not found. Please sign up at https://partners.shopify.com/signup
> For authentication issues, run shopify logout to clear invalid credentials
> Logged into store <redacted>.myshopify.com as staff (no partner organizations available for this login)
> ```
> 
> Kinda funny.

Thanks for following up and confirming that the fix works for you! The message does seem odd 😅 I suspect it might be an older error message. I will make a note of that.

**Comment by hannachen** [comment]
> > Hello, the latest update to the Shopify CLI addresses a bug which appears to allow you to log into any store (but does not allow you to take actions in stores you don't have access to).
> > Those impacted by this fix might be a group of accounts that **uses the same email for both merchant store and partners account**.
> > Recommendations:
> > 
> > * Change your partner organization email to be different from your merchant/collaborator account
> > * Change your collaborator account email address to be different from your partner organization account
> 
> @hannachen does this mean that the current 'issue' is actually expected functionality? I am a little unsure of how this addresses the problem though. In the original issue report we are referring to a store that we do not have collaborator access to. We only have direct user access, and the user does have the themes permission. Previously we had no trouble logging into this account on shopify-cli, but since 2.9.0 we get the error shown in the issue report description.
> 
> Is this expected behaviour? Does shopify-cli now require that we have a collaborator account to log in to any stores?

Hi @lesterdefreitas, yes, the "issue" was actually a fix for another bug caused by more strict access control, as the collaborator account is something introduced in fall 2020. For a while, the login feature was fairly lenient with checks, but this has been tightened up since.

**Comment by hannachen** [comment]
> I am new to using Shopify CLI, Just installed it on my WINDOWS 10 machine.
> 
> When I use the command `shopify login`
> 
> It takes me to the login page. But when I click login it's showing `{"code":"MethodNotAllowed","message":"GET is not allowed"}`
> 
> Is there anything I am missing?

This sounds a bit similar to this issue reported, there might be some issues specifically with Windows 10 and the CLI: https://github.com/Shopify/shopify-cli/issues/1935

**Comment by lesterdefreitas** [comment]
> @lesterdefreitas and @ettoredn - can you confirm what type of accounts you're using to log-in to your Plus vs non-Plus stores? Are you using staff member accounts for the Plus stores and collaborator accounts for the non-Plus stores?

@stephszeto in our case we are logging in to a Plus store with a staff account that has themes permission. We do not have a collaborator access for the store currently so the user account is out only option. It has always worked in the past, and is still [stated as a valid login permissions in the documentation for shopify-cli](https://shopify.dev/themes/tools/cli/getting-started#:~:text=or%20a%20staff%20account%20with%20the%20Manage%20themes%20permission%20or%20Themes%20permission), so to me it feels like a bug that it is [warning us that the store url is incorrect](https://github.com/Shopify/shopify-cli/issues/1944#:~:text=This%20is%20the,with%20the%20asterisks) and not allowing us to proceed.

On my Windows PC I have rolled back to cli 2.8.0 (ruby makes this easy) so that I can continue working on this client's store. However on my Mac I am locked out as Homebrew has no easy roll back function for shopify-cli.

**Comment by ronnross** [comment]
I agree with the folks above that is would be fantastic be able to role back with Homebrew when one experiences an issue. 

I'm seeing the same issue as above. I just have a staff account. So no partner account, but yet I see the same error as above. 

`Invalid store provided (xxxxxxxxxxx.myshopify.com). Please make sure that the store belongs to your partner organization, and provide the store in the following format: my-store.myshopify.com`

Worked yesterday. Updated to 2.9 today and not longer works. 

I'm on Mac OSX.

**Comment by lesterdefreitas** [comment]
**UPDATE:** With the release of 2.10.0 today this issue seems to be resolved. Can anyone else who was experiencing this issue confirm if it is working for them as well?

@hannachen So I'm assuming that this was a bug then and not a security feature as [previously suggested](https://github.com/Shopify/shopify-cli/issues/1944#issuecomment-1020343943)?

**Comment by amcaplan** [comment]
Closing this issue as it seems to be resolved.

**Comment by iamrobreynolds** [comment]
I don't know if this is related or not, but I'm not able to login to our store. I have a staff account on Shopify Plus with all permissions.

Running Linux Manjaro 21.2.2 Gnome 41.3

```
✗ An unexpected error occured.
	To submit an issue include the stack trace.
	To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

** [Bugsnag] 2022-02-15 22:55:29 -0500: Unable to send information to Bugsnag (https://notify.bugsnag.com), #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=[2600:1901:0:a5e4::]:443 state=error: certificate verify failed (unable to get local issuer certificate)>
** [Bugsnag] 2022-02-15 22:55:29 -0500: ["/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/protocol.rb:46:in `connect_nonblock'", "/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/protocol.rb:46:in `ssl_socket_connect'", "/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/http.rb:1048:in `connect'", "/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/http.rb:976:in `do_start'", "/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/http.rb:965:in `start'", "/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/http.rb:1530:in `request'", "/home/robbie/.gem/gems/bugsnag-6.24.2/lib/bugsnag/delivery/synchronous.rb:51:in `request'", "/home/robbie/.gem/gems/bugsnag-6.24.2/lib/bugsnag/delivery/synchronous.rb:12:in `deliver'", "/home/robbie/.gem/gems/bugsnag-6.24.2/lib/bugsnag/delivery/thread_queue.rb:38:in `block in serialize_and_deliver'", "/home/robbie/.gem/gems/bugsnag-6.24.2/lib/bugsnag/delivery/thread_queue.rb:55:in `block (2 levels) in start_once!'"]
```
```
shopify system all                                                                                                    ✔  system  
Environment
  TERM              = xterm-256color
  SHELL             = /bin/zsh
  PATH              = /home/robbie/.local/bin:/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/robbie/.gem/bin:/home/robbie/.gem/bin
  LANG              = en_US.UTF-8

Shopify CLI
               ROOT = /home/robbie/.gem/gems/shopify-cli-2.11.2
  PROJECT_TYPES_DIR = /home/robbie/.gem/gems/shopify-cli-2.11.2/lib/project_types
           TEMP_DIR = /home/robbie/.gem/gems/shopify-cli-2.11.2/.tmp
          CACHE_DIR = /home/robbie/.cache/shopify
   TOOL_CONFIG_PATH = /home/robbie/.config/shopify
           LOG_FILE = /home/robbie/.config/shopify/logs/log.log
     DEBUG_LOG_FILE = /home/robbie/.config/shopify/logs/debug.log

Current Shop
  No store found. Please run shopify login --store=STORE to login to a specific store

Ruby (via RbConfig)
  /var/lib/snapd/snap/ruby/247/bin/ruby
  x86_64-pc-linux-gnu       - RbConfig["host"]
  ruby-3.1.0                - RbConfig["RUBY_VERSION_NAME"]

Commands
  ✓ git, /usr/bin/git
  ✓ curl, /usr/bin/curl
  ✓ tar, /usr/bin/tar
```

**Comment by iamrobreynolds** [comment]
> @iamrobreynolds I'd recommend opening a new issue with full details, as this issue is closed and was solved with the release of 2.10.0.
> 
> @gonzaloriestra note this user had an issue with bugsnag, I wonder if this is something which would prevent downstream things from occurring. Might be worth adding a `rescue` before [this LOC](https://github.com/Shopify/shopify-cli/blob/a89bc74a4547ad8d28cb777beac548608be15f5b/lib/shopify_cli/exception_reporter.rb#L49).

Thank you for your response. I've submitted the issue -> https://github.com/Shopify/shopify-cli/issues/2065
