### ISSUE TITLE
`switch` command with `store` flag fails

### ISSUE THREAD

**Issue by aidantjones** [Shopify/shopify-cli#1948]
# Issue summary

Attempting to switch stores when logged into a partner organization fails.

Replacing the file `/usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/lib/shopify_cli/commands/login.rb` with the version from the 2.8.0 release fixes the issue.

So it seems there was a bug introduced in the 2.9.0 release.

## Expected behavior

Running `shopify switch` with a `store` flag containing a valid value should switch the current development stores to that store.

## Actual behavior

`✗ An unexpected error occured.`

## Steps to reproduce the problem

1. Log into a partners account with `shopify login`. 
2. Attempt to switch to a store to which the current user has managed store access using `shopify switch --store`.

## Stacktrace

```
/usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/lib/shopify_cli/commands/login.rb:45:in `validate_shop': wrong number of arguments (given 1, expected 0; required keywords: shop, org, context) (ArgumentError)                                                            
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/lib/shopify_cli/commands/switch.rb:19:in `call'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/lib/shopify_cli/command.rb:30:in `call'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/lib/shopify_cli/core/executor.rb:15:in `call'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/lib/shopify_cli/core/monorail.rb:30:in `log'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/bin/shopify:37:in `block (2 levels) in <top (required)>'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/bin/shopify:36:in `block in <top (required)>'
        from /usr/local/Cellar/shopify-cli/2.9.0/gems/shopify-cli-2.9.0/bin/shopify:47:in `<top (required)>'
        from /usr/local/bin/shopify:7:in `load'
        from /usr/local/bin/shopify:7:in `<main>'
```

## Specifications

- App type: shopify-cli 2.9.0
- Operating System: macOS 12.0.1
- Shell: zsh 5.8 (x86_64-apple-darwin21.0)
- Ruby version (ruby -v): ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]

**Comment by HauntedSmores** [comment]
Same issues here. For now, I have to `shopify logout` and `shopify login --store` each time, which forces you to redeploy the dev theme.

**Comment by amcaplan** [comment]
@aidantjones @michaelburtonray @joaopedrogomes @danniel917 @HauntedSmores there were changes to authentication in 2.9.0 that have been reverted as of 2.10.0. If you download the latest version of the CLI things should work as before.

The context was that there was a fix for a bug that let you seem to be logged into a store but then you weren't actually logged in. However, this had an unintentional side effect which sometimes blocks login entirely.

You can read more details in [this issue](https://github.com/Shopify/shopify-cli/issues/1944).

Closing this issue; feel free to open another if problems persist.

**Comment by HauntedSmores** [comment]
@amcaplan Can confirm this works now on 2.10.2
