### ISSUE TITLE
`theme check` fails with `--fail-level suggestion` argument

### ISSUE THREAD

**Issue by kilgore5** [Shopify/shopify-cli#1972]
# Issue summary
When running `theme check` with `--fail-level suggestion` arg, when `suggestion: MissingTemplate` is found, an `unexpected error` occurs.

## Expected behavior

Expect `unexpected error` not to be raised.

## Actual behavior
`✗ An unexpected error occured.`

## Steps to reproduce the problem

1. reference unavailable snippet in theme.liquid, e.g. `{%- render 'baz-bop' -%}`
2. run `SHOPIFY_CLI_STACKTRACE=1 shopify theme check --fail-level suggestion`
3. result
```
$ SHOPIFY_CLI_STACKTRACE=1 shopify theme check --fail-level suggestion --config .config/.theme-check.yml
Checking . ...
layout/theme.liquid:23: suggestion: MissingTemplate: 'snippets/baz-bop.liquid' is not found.
	{%- render 'baz-bop' -%}
	    ^^^^^^^^^^^^^^^^^

1039 files inspected, 1 offenses detected, 1 offenses auto-correctable
✗ An unexpected error occured.
	To submit an issue include the stack trace.

? Send an anonymized error report to Shopify? (You chose: Yes, send)
```

## Stacktrace
no stack trace available, despite running with `SHOPIFY_CLI_STACKTRACE=1`

## Specifications

- CLI version 2.9.0, installed via Brew
- Operating System: OSX 10.14
- Shell: Bash

**Comment by lorand-horvath** [comment]
What theme-check version are you using?
Also, have you tried updating shopify-cli to 2.10.1?

**Comment by kilgore5** [comment]
switching to latest `shopify-cli` / `theme-check` gems (that I can see), I still get the same result (same replication steps as above)...
```
Johns-MacBook-Pro:sb2_fresh johnroyall$ which shopify
/Users/johnroyall/.rvm/gems/ruby-2.6.3/bin/shopify
Johns-MacBook-Pro:sb2_fresh johnroyall$ shopify version
⭑ You are running a development version of the CLI at:
  /Users/johnroyall/shopify-cli-kilgore5/bin/shopify

2.10.2
Johns-MacBook-Pro:sb2_fresh johnroyall$ cat Gemfile.lock | grep 'theme-check'
      theme-check (~> 1.9.0)
    theme-check (1.9.2)
```


This time I do get an error backtrace... `lib/shopify_cli/github/issue_url_generator.rb:14:in `error_url': undefined method `length' for nil:NilClass (NoMethodError)`

full backtrace...
```
johnroyall$ shopify theme check --fail-level suggestion --config .config/.theme-check.yml
Checking . ...
layout/theme.liquid:30: suggestion: MissingTemplate: 'snippets/baz-bop.liquid' is not found.
  {%- render 'baz-bop' -%}
      ^^^^^^^^^^^^^^^^^

1062 files inspected, 1 offenses detected, 1 offenses auto-correctable
✗ An unexpected error occured.
Traceback (most recent call last):
  30: from /.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
  29: from /.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
  28: from /.rvm/gems/ruby-2.6.3/bin/shopify:23:in `<main>'
  27: from /.rvm/gems/ruby-2.6.3/bin/shopify:23:in `load'
  26: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/bin/shopify:47:in `<top (required)>'
  25: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/bin/shopify:36:in `block in <top (required)>'
  24: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
  23: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
  22: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/bin/shopify:37:in `block (2 levels) in <top (required)>'
  21: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/core/entry_point.rb:23:in `call'
  20: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/core/monorail.rb:30:in `log'
  19: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
  18: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/core/executor.rb:15:in `call'
  17: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
  16: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
  15: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
  14: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
  13: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
  12: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/core/executor.rb:16:in `block in call'
  11: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
  10: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
   9: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
   8: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
   7: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
   6: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
   5: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/command.rb:24:in `call'
   4: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/command/sub_command.rb:14:in `call'
   3: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/project_types/theme/commands/check.rb:25:in `call'
   2: from /.rvm/gems/ruby-2.6.3/gems/theme-check-1.9.2/lib/theme_check/cli.rb:127:in `run'
   1: from /.rvm/gems/ruby-2.6.3/gems/theme-check-1.9.2/lib/theme_check/cli.rb:123:in `run!'
/.rvm/gems/ruby-2.6.3/gems/theme-check-1.9.2/lib/theme_check/cli.rb:198:in `check': ThemeCheck::Cli::Abort
  30: from /.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
  29: from /.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
  28: from /.rvm/gems/ruby-2.6.3/bin/shopify:23:in `<main>'
  27: from /.rvm/gems/ruby-2.6.3/bin/shopify:23:in `load'
  26: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/bin/shopify:47:in `<top (required)>'
  25: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/bin/shopify:36:in `block in <top (required)>'
  24: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
  23: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
  22: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/bin/shopify:37:in `block (2 levels) in <top (required)>'
  21: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/core/entry_point.rb:23:in `call'
  20: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/core/monorail.rb:30:in `log'
  19: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
  18: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/core/executor.rb:15:in `call'
  17: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
  16: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
  15: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
  14: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
  13: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
  12: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/core/executor.rb:16:in `block in call'
  11: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
  10: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
   9: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
   8: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
   7: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
   6: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
   5: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/command.rb:24:in `call'
   4: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/command/sub_command.rb:14:in `call'
   3: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/project_types/theme/commands/check.rb:25:in `call'
   2: from /.rvm/gems/ruby-2.6.3/gems/theme-check-1.9.2/lib/theme_check/cli.rb:126:in `run'
   1: from /.rvm/gems/ruby-2.6.3/gems/theme-check-1.9.2/lib/theme_check/cli.rb:131:in `rescue in run'
/.rvm/gems/ruby-2.6.3/gems/theme-check-1.9.2/lib/theme_check/cli.rb:131:in `exit': exit (SystemExit)
  3: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:71:in `block in install!'
  2: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:31:in `handle_exception'
  1: from /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/exception_reporter.rb:8:in `report'
/.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/github/issue_url_generator.rb:10:in `error_url': undefined method `length' for nil:NilClass (NoMethodError)
```

**Comment by lorand-horvath** [comment]
@kilgore5 Just wondering why are you still using Ruby 2.6 ?
@pepicrft recommends we should be using 2.7 or 3.0 https://github.com/Shopify/shopify-cli/issues/1931#issuecomment-1014315157

**Comment by charlespwd** [comment]
> /.rvm/gems/ruby-2.6.3/gems/shopify-cli-2.10.2/lib/shopify_cli/github/issue_url_generator.rb:10:in `error_url': undefined method `length' for nil:NilClass (NoMethodError)

Thanks for the trace! That helps!

Looks like it's because we Abort without an error message maybe? Feels like the CLI thinks that it's a bug when it's intended behaviour @amcaplan 

Don't think we should even be calling issue_url_generator.

**Comment by charlespwd** [comment]
Right. But I think in this case that's intended behaviour? The way theme-check works in CI is that it has exit code 1 for lint errors, exit code 2 for theme-check errors and exit code 0 for success. The --fail-level flag here adjusts which level is considered an error.

Maybe what we really need to do is handle this case? I feel like something is not being caught or wrapped in a shopify CLI manner here.

**Comment by amcaplan** [comment]
@charlespwd that makes sense as well. Perhaps we need to add some error handling here, what would you suggest? https://github.com/Shopify/shopify-cli/blob/c0c5a8e46553fc470c70a176a89b77c0f7f884f2/lib/project_types/theme/commands/check.rb#L27-L29

**Comment by charlespwd** [comment]
You can probably redo what we do in run and call run! instead.

**Comment by amcaplan** [comment]
Et voila https://github.com/Shopify/shopify-cli/pull/2018

Thanks for the suggestion, @charlespwd!
