### ISSUE TITLE
OS Runtime Error x64-mingw-ucrt (RuntimeError) - Windows

### ISSUE THREAD

**Issue by HeavenlyEntity** [Shopify/shopify-cli#1990]
# Issue summary
When trying to check the version number of `shopify` execution on Windows a Runtime error occurs.

## Expected behavior

The run of `$ shopify version` should follow with the correct information.

```shell
2.10.1
Automatically send anonymized usage and error reports to Shopify? We use these to make development on Shopify better.
```

## Actual behavior

When `shopify version` is ran after an install on a windows machine the following error occurs:

```shell
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/vendor/deps/cli-ui/lib/cli/ui/os.rb:15:in `current': Could not determine OS from platform x64-mingw-ucrt (RuntimeError)
```

## Steps to reproduce the problem

1. Install [ruby installer dev kit](https://rubyinstaller.org/downloads/)
2. Make sure to leave all boxes checked durring install.
3. Start PowerShell Admin terminal 
4. Run `gem install shopify-cli`
5. Restart terminal after install
6. Run `shopify version`

✔ **SOLUTION TO ISSUE STEPS**: 
1. Navigate to:
```shell
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.7.4/vendor/deps/cli-ui/lib/cli/ui/
```
2. Open file `os.rb` in your code editor
3. Navigate to line `12` 
4. **Change:** 
```ruby
when /mingw32/
          Windows
```
**to:**
```ruby
when /mingw/
          Windows
```
5. Save the file
6. Restart terminal
7. Run `shopify version`

## Stacktrace

```shell

C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/vendor/deps/cli-ui/lib/cli/ui/os.rb:15:in `current': Could not determine OS from platform x64-mingw-ucrt (RuntimeError)
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/vendor/deps/cli-ui/lib/cli/ui/spinner.rb:13:in `<module:Spinner>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/vendor/deps/cli-ui/lib/cli/ui/spinner.rb:6:in `<module:UI>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/vendor/deps/cli-ui/lib/cli/ui/spinner.rb:5:in `<module:CLI>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/vendor/deps/cli-ui/lib/cli/ui/spinner.rb:4:in `<top (required)>'
        from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/bin/shopify:9:in `require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/vendor/deps/cli-ui/lib/cli/ui.rb:19:in `<module:UI>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/vendor/deps/cli-ui/lib/cli/ui.rb:2:in `<module:CLI>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/vendor/deps/cli-ui/lib/cli/ui.rb:1:in `<top (required)>'
        from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/bin/shopify:9:in `require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/lib/shopify_cli.rb:25:in `<top (required)>'
        from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/bin/shopify:9:in `require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/bin/load_shopify.rb:18:in `<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/bin/shopify:32:in `require_relative'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.10.1/bin/shopify:32:in `<top (required)>'
        from C:/Ruby31-x64/bin/shopify:25:in `load'
        from C:/Ruby31-x64/bin/shopify:25:in `<main>'
```

## Specifications

- App type: Shopify-CLI 2.10.1
- Operating System: Windows 10 Pro 64-bit
- Shell: CMD/Powershell
- Ruby version (ruby -v): 3.1.0

**Comment by HeavenlyEntity** [comment]
Not sure what you guys have to do to make this compatible with x64 based windows systems but thought I should put this out there to bring to your attention. 👍

**Comment by HeavenlyEntity** [comment]
Hello.
I have the same problem.
My ruby version is 3.1.0 and shopify cli version is 2.10.0.
Could you please help me.
Thanks.

_Originally posted by @puma1027 in https://github.com/Shopify/shopify-cli/issues/1960#issuecomment-1023935875_

**Comment by HeavenlyEntity** [comment]
Related to #1983

**Comment by lorand-horvath** [comment]
The issue seem to come from using the very latest Ruby 3.1, which is not yet recommended by the developers. Only 2.7 and 3.0 are fully tested against according to https://github.com/Shopify/shopify-cli/issues/1931
