### ISSUE TITLE
[Bug]: `shopify theme serve` fails

### ISSUE THREAD

**Issue by mcoppola** [Shopify/shopify-cli#2017]
### Before jumping to submit...

- [X] I've searched the [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if someone else has already submitted the same thing. (Feel free to add any additional information in a comment!)
- [X] I've given as much detail as reasonably possible
- [X] I've tested with the [latest CLI version](https://github.com/Shopify/shopify-cli/releases)

### What type of project are you working on?

theme

### Issue summary

Unable to run `shopify theme serve` with fresh cli install and unmodified Dawn theme code

### Expected behavior

command produces a local instance of the shop with the theme applied

### Actual behavior

command fails. the stacktrace reveals that it's failing on the JSON.generate in the theme.create script
```ruby
def create
    raise InvalidThemeRole, "Can't create live theme. Use publish." if live?

    _status, body = ShopifyCLI::AdminAPI.rest_request(
      @ctx,
      shop: shop,
      path: "themes.json",
      body: JSON.generate({
        theme: {
          name: name,
          role: role,
        },
      }),
      method: "POST",
      api_version: "unstable",
    )

    @id = body["theme"]["id"]
  end
```

### Stack trace

```shell
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/json/common.rb:312:in `generate': "\\xE2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
        from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/json/common.rb:312:in `generate'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/lib/shopify_cli/theme/theme.rb:108:in `create'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/lib/shopify_cli/theme/development_theme.rb:37:in `ensure_exists!'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/lib/shopify_cli/theme/dev_server.rb:44:in `start'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/lib/project_types/theme/commands/serve.rb:19:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/lib/shopify_cli/command/sub_command.rb:14:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/lib/shopify_cli/command.rb:24:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/lib/shopify_cli/core/executor.rb:16:in `block in call'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/lib/shopify_cli/core/executor.rb:15:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/lib/shopify_cli/core/monorail.rb:30:in `log'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/lib/shopify_cli/core/entry_point.rb:23:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/bin/shopify:37:in `block (2 levels) in <top (required)>'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/bin/shopify:36:in `block in <top (required)>'
	from /opt/homebrew/Cellar/shopify-cli/2.10.2/gems/shopify-cli-2.10.2/bin/shopify:47:in `<top (required)>'
	from /opt/homebrew/bin/shopify:7:in `load'
	from /opt/homebrew/bin/shopify:7:in `<main>'
```

### Reproduction steps

1. install shopify-cli via homebrew
```
brew tap shopify/shopify
brew install shopify-cli
```
2. download template them
```
shopify theme init my-shop-name
```
3. login to shopify account
```
shopify login --store my-shop-name.myshopify.com
```
4. serve theme
```
cd my-shop-name
shopify theme serve
```

### Operating System

Mac OS 12.2

### CLI version (run `shopify version` if you're not sure)

2.10.2

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

ruby 3.0.0p0

**Comment by mcoppola** [comment]
This is caused by an apostrophe (') in the computer's name, which is default for osx. 
<img width="667" alt="Screenshot 2022-02-05 at 18 10 11@2x" src="https://user-images.githubusercontent.com/2504594/152662040-36f8028c-951a-40a1-84b1-a4db2e95191a.png">

 I was to work around the issue by hard coding the `name` in the `theme.rb` script.
