### ISSUE TITLE
[Bug]: Node is required for all the commands

### ISSUE THREAD

**Issue by sm-12** [Shopify/shopify-cli#2039]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

other

### Expected behavior

shopify login

### Actual behavior

C:\Users\sayum>shopify login
X An unexpected error occured.
        To ]8;;https://github.com/Shopify/shopify-cli/issues/new?title=%5BBug%5D%3A+Errno%3A%3AENOENT%3A+No+such+file+or+directory+-+node&labels=type%3Abug&template=bug_report.yaml&stack_trace=C%3A%2FRuby27-x64%2Flib%2Fruby%2F2.7.0%2Fopen3.rb%3A213%3Ain+%60spawn%27%0AC%3A%2FRuby27-x64%2Flib%2Fruby%2F2.7.0%2Fopen3.rb%3A213%3Ain+%60popen_run%27%0AC%3A%2FRuby27-x64%2Flib%2Fruby%2F2.7.0%2Fopen3.rb%3A101%3Ain+%60popen3%27%0AC%3A%2FRuby27-x64%2Flib%2Fruby%2F2.7.0%2Fopen3.rb%3A281%3Ain+%60capture3%27%0AC%3A%2FRuby27-x64%2Flib%2Fruby%2Fgems%2F2.7.0%2Fgems%2Fshopify-cli-2.11.1%2Fvendor%2Fdeps%2Fcli-kit%2Flib%2Fcli%2Fkit%2Fsystem.rb%3A199%3Ain+%60delegate_open3%27&os=x64-mingw32&cli_version=2.11.1&ruby_version=2.7.5p203&shell\submit an issue]8;;\ include the stack trace.

### Stack trace

```shell
Traceback (most recent call last):
        32: from C:/Ruby27-x64/bin/shopify:23:in `<main>'
        31: from C:/Ruby27-x64/bin/shopify:23:in `load'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/bin/shopify:47:in `<top (required)>'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/bin/shopify:36:in `block in <top (required)>'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/bin/shopify:37:in `block (2 levels) in <top (required)>'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/lib/shopify_cli/core/entry_point.rb:23:in `call'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/lib/shopify_cli/core/monorail.rb:30:in `log'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/lib/shopify_cli/core/executor.rb:15:in `call'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/lib/shopify_cli/core/executor.rb:16:in `block in call'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/lib/shopify_cli/command.rb:33:in `call'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/lib/shopify_cli/command.rb:109:in `check_node_version'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/lib/shopify_cli/environment.rb:22:in `node_version'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/lib/shopify_cli/context.rb:557:in `capture3'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/system.rb:90:in `capture3'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/system.rb:199:in `delegate_open3'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:281:in `capture3'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:101:in `popen3'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - node (Errno::ENOENT)
```

### Reproduction steps

1.gem install shopify-cli
2.shopify login
3.

### Operating System

x64-mingw32

### CLI version (run `shopify version` if you're not sure)

2.11.1

### Ruby version (run `ruby -v` if you're not sure)

2.7.5p203

**Comment by gonzaloriestra** [comment]
It looks like, since v2.11.0, we are requiring Node for some operations that don't really need it. As a workaround while we fix it, you could just install it or downgrade to v2.10.2. Sorry for the inconvenience.

**Comment by gonzaloriestra** [comment]
The issue should be fixed in [version 2.11.2](https://github.com/Shopify/shopify-cli/releases/tag/v2.11.2).

**Comment by gonzaloriestra** [comment]
@ADTC but is it showing `No such file or directory - node`? Do you have the version 2.11.2? Could you share the stack trace?

The supported Node versions are between 14.5 and 17.0, but it should only be required to create Node or Rails apps.

**Comment by ADTC** [comment]
@gonzaloriestra thank you for such a quick response! I downgraded to 2.10.2 but it still didn't work. I then downgraded to the last known working version 2.10.0 and it still didn't work! Uninstalling all shopify-cli gems and reinstalling also didn't work.

```
> shopify
X An unexpected error occured.
        To submit an issue include the stack trace.

Traceback (most recent call last):
        27: from C:/Ruby27-x64/bin/shopify:23:in `<main>'
        26: from C:/Ruby27-x64/bin/shopify:23:in `load'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/bin/shopify:56:in `<top (required)>'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/bin/shopify:45:in `block in <top (required)>'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/bin/shopify:46:in `block (2 levels) in <top (required)>'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/core/entry_point.rb:23:in `call'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/core/monorail.rb:30:in `log'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/core/executor.rb:15:in `call'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/core/executor.rb:16:in `block in call'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/command.rb:32:in `call'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/command.rb:82:in `check_ruby_version'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/environment.rb:18:in `ruby_version'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/lib/shopify_cli/environment.rb:18:in `new'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.11.2/vendor/lib/semantic/version.rb:15:in `initialize': Initializing... (ArgumentError)
2.7.2 is not a valid SemVer Version (http://semver.org)
```

**Comment by ADTC** [comment]
What is this `SemVer` 💩? Should I open a new issue?

**Comment by ADTC** [comment]
@gonzaloriestra ?
