### ISSUE TITLE
[Bug]: Errno::ENOENT: No such file or directory - node

### ISSUE THREAD

**Issue by yw6870** [Shopify/shopify-cli#2043]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Run the `shopify version` command to check the version of the shopify CLI.

### Actual behavior

"✗ An unexpected error occured.To submit an issue include the stack trace."
An error was displayed.

### Stack trace

```shell
/Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/3.1.0/open3.rb:222:in `spawn': No such file or directory - node (Errno::ENOENT)
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/3.1.0/open3.rb:222:in `popen_run'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/3.1.0/open3.rb:103:in `popen3'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/3.1.0/open3.rb:290:in `capture3'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/system.rb:199:in `delegate_open3'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/system.rb:90:in `capture3'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/lib/shopify_cli/context.rb:557:in `capture3'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/lib/shopify_cli/environment.rb:22:in `node_version'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/lib/shopify_cli/command.rb:109:in `check_node_version'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/lib/shopify_cli/command.rb:33:in `call'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/lib/shopify_cli/core/executor.rb:16:in `block in call'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/lib/shopify_cli/core/executor.rb:15:in `call'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/lib/shopify_cli/core/monorail.rb:30:in `log'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/lib/shopify_cli/core/entry_point.rb:23:in `call'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/bin/shopify:37:in `block (2 levels) in <top (required)>'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/bin/shopify:36:in `block in <top (required)>'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/shopify-cli-2.11.1/bin/shopify:47:in `<top (required)>'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/bin/shopify:25:in `load'
	from /Users/yuyawatari/.rbenv/versions/3.1.0/bin/shopify:25:in `<main>'
```

### Reproduction steps

1.Enter one of the shopifyCLI commands
2.
3.

### Operating System

arm64-darwin21

### CLI version (run `shopify version` if you're not sure)

2.11.1

### Shell

/bin/zsh

### Ruby version (run `ruby -v` if you're not sure)

3.1.0p0

**Comment by inex0rable** [comment]
Shopify have historically fallen a little short with helpful error handling. If I recall, this used to happen if nodejs wasn't installed. Maybe check that first.

**Comment by gonzaloriestra** [comment]
Duplicate of https://github.com/Shopify/shopify-cli/issues/2039
