### ISSUE TITLE
[Bug]: NoMethodError: undefined method `shop' for nil:NilClass

### ISSUE THREAD

**Issue by owenmcateer** [Shopify/shopify-cli#2059]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Expecting `shopify theme serve` to server the current theme.

### Actual behavior

```
shopify theme serve
✗ An unexpected error occured.
	To submit an issue include the stack trace.
	To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

? Send an anonymized error report to Shopify? (You chose: Yes, send)
```

### Stack trace

```shell
/Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.11.2/lib/shopify_cli/theme/dev_server.rb:83:in `rescue in start'
/Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.11.2/lib/shopify_cli/theme/dev_server.rb:29:in `start'
/Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.11.2/lib/project_types/theme/commands/serve.rb:21:in `call'
/Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.11.2/lib/shopify_cli/command/sub_command.rb:16:in `call'
/Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.11.2/lib/shopify_cli/command.rb:27:in `call'
```

### Reproduction steps

After install shopify-cli I ran:
1. shopify login --store=MYSTORE
2. shopify server

### Operating System

universal.x86_64-darwin21

### CLI version (run `shopify version` if you're not sure)

2.11.2

### Shell

/bin/zsh

### Ruby version (run `ruby -v` if you're not sure)

2.6.8p205

**Comment by Dima34** [comment]
Same problem

**Comment by owenmcateer** [comment]
I can confirm I have full access to edit the store and theme.

**Comment by Dima34** [comment]
* Tip from Themes Getting started docs. It helps me "
* You can't use Shopify CLI with development stores if you only have [Partner staff member](https://help.shopify.com/partners/dashboard/account-access) access. If you want to use Shopify CLI to work on a development store, then you should be the store owner or create a staff account on the store.

If you're the store owner, then you need to log in to the store directly using the store URL at least once (for example, using {shop}.myshopify.com/admin) before you log in using Shopify CLI. Logging in to the Shopify admin directly connects the development store with your Shopify login.
* "

**Comment by sc00** [comment]
Same issue. I'm the store owner and have logged into the CMS of the store.

`/opt/homebrew/Cellar/shopify-cli/2.11.2/gems/shopify-cli-2.11.2/lib/shopify_cli/theme/dev_server.rb:83:in `rescue in start': undefined method `shop' for nil:NilClass (NoMethodError)`

**Comment by sc00** [comment]
Creating a staff member with a different email address solved it for me.

**Comment by CHEWX** [comment]
I have the same problem, but I create a staff member with a different email address as above, this solved, however this is a workaround, it's not solved!

**Comment by vhtellez** [comment]
What worked for me:

1.   Command "shopify logout"
2.  Command "shopify login --store=STORE" 
3.  Command "shopify theme serve"

**Comment by p8ul** [comment]
For my case, I had to downgrade `shopify-cli`. 

```bash
gem uninstall shopify-cli

gem install shopify-cli -v 2.7.4 
```

**Comment by karreiro** [comment]
(If this issue gets re-opened, I will re-assign it to me @kilgore5. But, for now, it seems like you've solved it! 🎉)

**Comment by BryanCastro** [comment]
> (If this issue gets re-opened, I will re-assign it to me @kilgore5. But, for now, it seems like you've solved it! 🎉)

Nope still broken, not resolved

**Comment by CrawlingMango** [comment]
> What worked for me:
> 
> 1. Command "shopify logout"
> 2. Command "shopify login --store=STORE"
> 3. Command "shopify theme serve"

worked for me, I tried to roung "shopify login" without logging out my other shopify account
