### ISSUE TITLE
[Bug]: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=23.227.38.74:443 state=error: certificate verify failed (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by iamrobreynolds** [Shopify/shopify-cli#2065]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Issue shopify login command
Get authenticated
Gain access to store via shopify-cli
issue shopify-cli theme commands

### Actual behavior

Error message in the terminal, unable to login.

```
✗ An unexpected error occured.
	To submit an issue include the stack trace.
	To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

** [Bugsnag] 2022-02-15 22:55:29 -0500: Unable to send information to Bugsnag (https://notify.bugsnag.com), #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=[2600:1901:0:a5e4::]:443 state=error: certificate verify failed (unable to get local issuer certificate)>
** [Bugsnag] 2022-02-15 22:55:29 -0500: ["/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/protocol.rb:46:in `connect_nonblock'", "/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/protocol.rb:46:in `ssl_socket_connect'", "/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/http.rb:1048:in `connect'", "/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/http.rb:976:in `do_start'", "/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/http.rb:965:in `start'", "/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/http.rb:1530:in `request'", "/home/robbie/.gem/gems/bugsnag-6.24.2/lib/bugsnag/delivery/synchronous.rb:51:in `request'", "/home/robbie/.gem/gems/bugsnag-6.24.2/lib/bugsnag/delivery/synchronous.rb:12:in `deliver'", "/home/robbie/.gem/gems/bugsnag-6.24.2/lib/bugsnag/delivery/thread_queue.rb:38:in `block in serialize_and_deliver'", "/home/robbie/.gem/gems/bugsnag-6.24.2/lib/bugsnag/delivery/thread_queue.rb:55:in `block (2 levels) in start_once!'"]
```
```
shopify system all                                                                                                    ✔  system  
Environment
  TERM              = xterm-256color
  SHELL             = /bin/zsh
  PATH              = /home/robbie/.local/bin:/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/robbie/.gem/bin:/home/robbie/.gem/bin
  LANG              = en_US.UTF-8

Shopify CLI
               ROOT = /home/robbie/.gem/gems/shopify-cli-2.11.2
  PROJECT_TYPES_DIR = /home/robbie/.gem/gems/shopify-cli-2.11.2/lib/project_types
           TEMP_DIR = /home/robbie/.gem/gems/shopify-cli-2.11.2/.tmp
          CACHE_DIR = /home/robbie/.cache/shopify
   TOOL_CONFIG_PATH = /home/robbie/.config/shopify
           LOG_FILE = /home/robbie/.config/shopify/logs/log.log
     DEBUG_LOG_FILE = /home/robbie/.config/shopify/logs/debug.log

Current Shop
  No store found. Please run shopify login --store=STORE to login to a specific store

Ruby (via RbConfig)
  /var/lib/snapd/snap/ruby/247/bin/ruby
  x86_64-pc-linux-gnu       - RbConfig["host"]
  ruby-3.1.0                - RbConfig["RUBY_VERSION_NAME"]

Commands
  ✓ git, /usr/bin/git
  ✓ curl, /usr/bin/curl
  ✓ tar, /usr/bin/tar
```

### Stack trace

```shell
/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/protocol.rb:46:in `connect_nonblock'
/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/protocol.rb:46:in `ssl_socket_connect'
/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/http.rb:1048:in `connect'
/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
/var/lib/snapd/snap/ruby/247/lib/ruby/3.1.0/net/http.rb:965:in `start'
```

### Reproduction steps

1. gem install shopify-cli
2. shopify login --store={store-name}.myshopify.com
3. error emitted in terminal

**System Info:**
OS: Manjaro Linux x86_64 
Host: Razer Blade 15 Advanced Model (Mid 2021) - RZ09-0409 7.04 
Kernel: 5.15.21-1-MANJARO 
Packages: 1202 (pacman), 6 (flatpak), 10 (snap) 
Shell: zsh 5.8 
Resolution: 2560x1440 
DE: GNOME 41.3 
WM: Mutter 
WM Theme: Mojave-dark 
Theme: Mojave-dark [GTK2/3] 
Icons: McMojave-circle-dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz 
GPU: NVIDIA GeForce RTX 3070 Mobile / Max-Q 
GPU: Intel TigerLake-H GT1 [UHD Graphics] 
Memory: 3883MiB / 15740MiB 

### Operating System

x86_64-linux

### CLI version (run `shopify version` if you're not sure)

2.11.2

### Shell

/bin/zsh

### Ruby version (run `ruby -v` if you're not sure)

3.1.0p0

### What language and version are you using in your application?

html, javascript, css

**Comment by gonzaloriestra** [comment]
@iamrobreynolds thanks for creating the issue, I'll have a look. In the meantime, could you try with a different Ruby version? We don't fully support 3.1 yet.
