### ISSUE TITLE
[Bug]: NoMethodError: undefined method `shop' for nil:NilClass

### ISSUE THREAD

**Issue by jondotblack** [Shopify/shopify-cli#2094]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

I can `check` my theme, but if I want to `pull`, `push`, or `serve` I just get a generic error.  All other Shopify cli commands work fine.  I've tried Ruby versions 2.7.5, 3.0.0, 3.1.0 and same error every time.  Updated the Shopify CLI to the latest version.

### Actual behavior

```
~/**/** on main ● ? ❯ shopify theme serve
✗ An unexpected error occured.
	To submit an issue include the stack trace.
	To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.
```

### Stack trace

```shell
/opt/homebrew/Cellar/shopify-cli/2.12.0/gems/shopify-cli-2.12.0/lib/shopify_cli/theme/dev_server.rb:83:in `rescue in start'
/opt/homebrew/Cellar/shopify-cli/2.12.0/gems/shopify-cli-2.12.0/lib/shopify_cli/theme/dev_server.rb:29:in `start'
/opt/homebrew/Cellar/shopify-cli/2.12.0/gems/shopify-cli-2.12.0/lib/project_types/theme/commands/serve.rb:25:in `call'
/opt/homebrew/Cellar/shopify-cli/2.12.0/gems/shopify-cli-2.12.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
/opt/homebrew/Cellar/shopify-cli/2.12.0/gems/shopify-cli-2.12.0/lib/shopify_cli/command.rb:27:in `call'
```

### Reproduction steps

1. run theme command `pull`, `push`, or `serve`
2. see error message

### Operating System

arm64-darwin21

### CLI version (run `shopify version` if you're not sure)

2.12.0

### Shell

/bin/zsh

### Ruby version (run `ruby -v` if you're not sure)

3.0.3p157

**Comment by ReplicantDeckard** [comment]
This seems to relate to my own issue. When I contacted customer support I was told that creating a development store as a Partner, which makes me owner of the store, ought to be correct and allow me to use shopify-cli logged in with that Partner organization. But it does not seem to be so. Either what you and I were originally trying to do is expected behaviour and in fact this is a bug, or documentation is not correct as you surmise (confusing even the reps?).

To clarify, did you create a new Shopify Partner account with a separate email address and then invite this new account as staff? Then you authenticate in shopify-cli with this account and not the shop owner account?

Thanks.

#2093
