### ISSUE TITLE
[Bug]: Cannot perform theme operation in shopify-cli 403 permission denied. 

### ISSUE THREAD

**Issue by azure-architect** [Shopify/shopify-cli#2119]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

I would be able to push pull and serve themes to and from my local machine. 
Windows 10 fresh install
➜ shopify version
2.13.0
➜ ruby -v
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x64-mingw32]

### Actual behavior

$env:SHOPIFY_CLI_STACKTRACE=1
➜ shopify theme pull
X An unexpected error occured.
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/api.rb:74:in `block in request': 403 (ShopifyCLI::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}
        

### Stack trace

```shell
Traceback (most recent call last):
        43: from C:/Ruby27-x64/bin/shopify:23:in `<main>'
        42: from C:/Ruby27-x64/bin/shopify:23:in `load'
        41: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/bin/shopify:59:in `<top (required)>'
        40: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/bin/shopify:49:in `block in <top (required)>'
        39: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        38: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/core/monorail.rb:30:in `log'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/core/executor.rb:15:in `call'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/command.rb:27:in `call'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/project_types/theme/commands/pull.rb:40:in `call'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/project_types/theme/commands/pull.rb:89:in `find_theme'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/project_types/theme/commands/pull.rb:93:in `select_theme'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/form.rb:13:in `ask'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/project_types/theme/forms/select.rb:12:in `ask'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:100:in `ask'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:188:in `ask_interactive'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/project_types/theme/forms/select.rb:13:in `block in ask'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/project_types/theme/forms/select.rb:27:in `theme_presenters'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/project_types/theme/presenters/themes_presenter.rb:16:in `all'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/project_types/theme/presenters/themes_presenter.rb:28:in `all_themes'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/theme/theme.rb:167:in `all'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/theme/theme.rb:208:in `fetch_themes'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/admin_api.rb:95:in `rest_request'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/api.rb:89:in `request'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/api.rb:74:in `block in request': 403 (ShopifyCLI::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}
```

### Reproduction steps

1.shopify login --store lynn-dev-1
2.shopify theme pull
3.

### Operating System

Windows 10 Pro

### CLI version (run `shopify version` if you're not sure)

2.13

### Shell

powershell

### What language and version are you using in your application?

ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x64-mingw32]

**Comment by azure-architect** [comment]
Shopify web site asked me if I wanted to streamline login by linking my dev store and my partner account login which seems to have cleared up my cli 403 issue but it has created another situation where I cannot log into my store with the store password after running shopify theme serve....

**Comment by azure-architect** [comment]
Still hanging on this one....

**Comment by amcaplan** [comment]
Possibly related to https://github.com/Shopify/shopify-cli/issues/1694

**Comment by amcaplan** [comment]
Also note https://github.com/Shopify/shopify-cli/issues/1361#issuecomment-879426041 which may be relevant
