### ISSUE TITLE
I can't run the shopify theme serve command

### ISSUE THREAD

**Issue by Juliowebnet** [Shopify/shopify-cli#2152]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

this should run a local server for theme

### Actual behavior

An unexpected error occured
![Screen Shot 2022-03-14 at 12 24 50 AM](https://user-images.githubusercontent.com/51296726/158722828-2bc6efe4-c6e5-440a-8c62-9191d5868498.png)
.

### Stack trace

```shell
/opt/homebrew/Cellar/shopify-cli/2.12.0/gems/shopify-cli-2.12.8/lib/shopify_cli/theme/dev.
server.rb:83:in
rescue in snn
tor nilNouthodryr)

/opt/homebrew/Cellar/shopify-cli/2.12.0/gems/shopify-cli-2.12.0/lib/shopify_cli/api.rb:74:in"blockinrequest':403(ShopifyCLI::API::APIRequestForbiddenError)
pyyoys"
"Unauthorized Access"}
```

### Reproduction steps

1. run brew install shopify-cli
2. run shopify theme init
3. cd depart-lite
4. shopify login --store depart-literd.myshopify.com
5. shopify theme serve

### Operating System

Mac OS Monterey

### CLI version (run `shopify version` if you're not sure)

2.12.0

### Shell

bash

### Ruby version (run `ruby -v` if you're not sure)

2.6.8p205

**Comment by nutttaro** [comment]
It's working fine for 2.13.0 but after updated to 2.14.0 the `shopify theme serve` it's not working anymore.

### Operating System
Mac OS Monterey

### CLI version (run shopify version if you're not sure)
2.14.0

### Shell
bash

### Ruby version (run ruby -v if you're not sure)
3.0.2p107

**Comment by nutttaro** [comment]
@karreiro 
I updated to 2.15.0 and I still got an error.
I already tried 
```
shopify logout
shopify login --store {name}.myshopify.com
shopify theme pull
```
but it didn't work.

I tried `SHOPIFY_CLI_STACKTRACE=1 shopify theme pull`, 
I got error messages
```
/usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/file.rb:37:in `unlink': Directory not empty @ dir_s_rmdir - assets/slick (Errno::ENOTEMPTY)
```

I guess it's because `shopify theme pull` doesn't work in a directory that isn't empty (I need to update my local code). However, I tried `shopify theme pull` in an empty directory, and it's working fine.

After that `shopify theme serve` It's working on new directory also.


An unexpected error occured for `shopify theme pull` on directory that isn't empty.
```
/usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/file.rb:37:in `unlink': Directory not empty @ dir_s_rmdir - assets/slick (Errno::ENOTEMPTY)
        from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/file.rb:37:in `delete'
        from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/file.rb:37:in `delete'
        from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/syncer.rb:178:in `block in download_theme!'
        from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/syncer.rb:176:in `each'
        from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/syncer.rb:176:in `download_theme!'
        from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/project_types/theme/ui/sync_progress_bar.rb:11:in `public_send'
        from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/project_types/theme/ui/sync_progress_bar.rb:11:in `block in progress'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-ui/lib/cli/ui/progress.rb:34:in `progress'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/project_types/theme/ui/sync_progress_bar.rb:10:in `progress'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/project_types/theme/commands/pull.rb:53:in `block in call'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/project_types/theme/commands/pull.rb:52:in `call'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/command.rb:27:in `call'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/core/executor.rb:15:in `call'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/core/monorail.rb:26:in `log'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/bin/shopify:49:in `block in <top (required)>'
    from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/bin/shopify:59:in `<top (required)>'
    from /usr/local/bin/shopify:7:in `load'
    from /usr/local/bin/shopify:7:in `<main>'
```

An unexpected error occured for `shopify theme serve` on directory that isn't empty.
```
/usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/file.rb:23:in `read': Is a directory @ io_fread - assets/slick (Errno::EISDIR)
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/file.rb:23:in `read'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/file.rb:23:in `read'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/file.rb:69:in `checksum'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/syncer.rb:323:in `file_has_changed?'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/syncer.rb:207:in `enqueue'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/syncer.rb:65:in `block in enqueue_updates'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/syncer.rb:65:in `each'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/syncer.rb:65:in `enqueue_updates'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/syncer.rb:161:in `upload_theme!'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/project_types/theme/ui/sync_progress_bar.rb:11:in `public_send'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/project_types/theme/ui/sync_progress_bar.rb:11:in `block in progress'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-ui/lib/cli/ui/progress.rb:34:in `progress'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/project_types/theme/ui/sync_progress_bar.rb:10:in `progress'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/project_types/theme/commands/serve.rb:26:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/dev_server.rb:53:in `block in start'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/theme/dev_server.rb:49:in `start'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/project_types/theme/commands/serve.rb:25:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/command.rb:27:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/core/executor.rb:15:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/core/monorail.rb:26:in `log'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/bin/shopify:49:in `block in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.15.0/gems/shopify-cli-2.15.0/bin/shopify:59:in `<top (required)>'
	from /usr/local/bin/shopify:7:in `load'
	from /usr/local/bin/shopify:7:in `<main>'
```

**Comment by karreiro** [comment]
Thanks for sharing the stack, @nutttaro. I believe your theme has this directory: `assets/slick` (if I'm not missing something)

However, themes don't support subdirectories other than the ones listed here: https://shopify.dev/themes/architecture#directory-structure-and-component-types. So, probably removing that directory solves the issue.

Also, this PR https://github.com/Shopify/shopify-cli/pull/1934 introduces a better error message in such cases. Thus, the CLI will fail with a more helpful/friendly error message in the future.

**Comment by nutttaro** [comment]
That's awesome! for display the error message.
