### ISSUE TITLE
[Bug]: Can't Pull Development Stores

### ISSUE THREAD

**Issue by catboxer** [Shopify/shopify-cli#2180]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

I would log in to shopify 
Pull theme and then theme would pull down

### Actual behavior

✗ An unexpected error occured.

### Stack trace

```shell
/Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/api.rb:74:in `block in request': 403 (ShopifyCLI::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/api.rb:89:in `request'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/admin_api.rb:95:in `rest_request'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/theme/theme_admin_api.rb:36:in `rest_request'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/theme/theme_admin_api.rb:14:in `get'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/theme/theme.rb:202:in `fetch_themes'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/theme/theme.rb:159:in `all'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/project_types/theme/presenters/themes_presenter.rb:28:in `all_themes'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/project_types/theme/presenters/themes_presenter.rb:16:in `all'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/project_types/theme/forms/select.rb:27:in `theme_presenters'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/project_types/theme/forms/select.rb:13:in `block in ask'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:188:in `ask_interactive'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:100:in `ask'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/project_types/theme/forms/select.rb:12:in `ask'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/form.rb:13:in `ask'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/project_types/theme/commands/pull.rb:93:in `select_theme'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/project_types/theme/commands/pull.rb:89:in `find_theme'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/project_types/theme/commands/pull.rb:40:in `call'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/command/sub_command.rb:16:in `call'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/command.rb:27:in `call'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/core/executor.rb:15:in `call'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/core/monorail.rb:26:in `log'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/lib/shopify_cli/core/entry_point.rb:23:in `call'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/bin/shopify:50:in `block (2 levels) in <top (required)>'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/bin/shopify:49:in `block in <top (required)>'
        from /Users/macuser/.gem/ruby/3.1.1/gems/shopify-cli-2.15.1/bin/shopify:59:in `<top (required)>'
        from /Users/macuser/.gem/ruby/3.1.1/bin/shopify:25:in `load'
        from /Users/macuser/.gem/ruby/3.1.1/bin/shopify:25:in `<main>'
```

### Reproduction steps

1.shopify logout
2.shopify login --store=storename.myshopify.com
3. browser window comes up. I log in and get Authenticated successfully. You may now close this page.
4. I am successfully logged in
5. shopify theme pull
Get error ✗ An unexpected error occured.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

### Operating System

Mac os catalina

### CLI version (run `shopify version` if you're not sure)

2.15.1

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

ruby 3.1.1p18

**Comment by catboxer** [comment]
I forgot to mention that I had already tried to log into my store directly through the store.myshopify.com/admin url but was rejected. 

I called your partner support and they told me "17:03 Alex K (Support Advisor): You can only log in through your partner account, this is a development store, only the partner account will have access to the store."

<img width="1301" alt="Screen Shot 2022-03-26 at 8 21 37 AM" src="https://user-images.githubusercontent.com/70821412/160246182-a0636e60-6843-4085-b953-375a0e4d2cca.png">

**Comment by catboxer** [comment]
Finally figured this out. Just needed to go in through an incognito browser. Hope this helps someone else down the line. 🤦
