### ISSUE TITLE
[Bug]: <Shopifycli theme serve error>

### ISSUE THREAD

**Issue by idemmanuel001** [Shopify/shopify-cli#2181]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

It should load up the theme and give a link to view my theme locally

### Actual behavior

It throws an error
```
X An unexpected error occured.
        To submit an issue include the stack trace.
```

### Stack trace

```shell
X An unexpected error occured.
        To submit an issue include the stack trace.

C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/theme/dev_server.rb:83:in `rescue in start': undefined method `shop' for nil:NilClass (NoMethodError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/theme/dev_server.rb:29:in `start'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/project_types/theme/commands/serve.rb:25:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/command/sub_command.rb:16:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/command.rb:27:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/core/executor.rb:15:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/core/monorail.rb:26:in `log'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/core/entry_point.rb:23:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/bin/shopify:50:in `block (2 levels) in <top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/bin/shopify:49:in `block in <top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/bin/shopify:59:in `<top 
(required)>'
        from C:/Ruby30-x64/bin/shopify:23:in `load'
        from C:/Ruby30-x64/bin/shopify:23:in `<main>'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/api.rb:74:in `block in request': 403 (ShopifyCLI::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/api.rb:89:in `request'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/admin_api.rb:95:in `rest_request'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/theme/theme_admin_api.rb:36:in `rest_request'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/theme/theme_admin_api.rb:14:in `get'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/theme/development_theme.rb:48:in `exists?'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/theme/development_theme.rb:34:in `ensure_exists!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/theme/development_theme.rb:71:in `find_or_create!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/theme/dev_server.rb:31:in `start'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/project_types/theme/commands/serve.rb:25:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/command/sub_command.rb:16:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/command.rb:27:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/core/executor.rb:15:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/core/monorail.rb:26:in `log'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/lib/shopify_cli/core/entry_point.rb:23:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/bin/shopify:50:in `block (2 levels) in <top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/bin/shopify:49:in `block in <top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.15.1/bin/shopify:59:in `<top 
(required)>'
        from C:/Ruby30-x64/bin/shopify:23:in `load'
        from C:/Ruby30-x64/bin/shopify:23:in `<main>'
```

### Reproduction steps

1. run theme init
2. cd into theme directory
3. login to your store using the owners account
4. run ``` shopify theme serve```

### Operating System

windows 10

### CLI version (run `shopify version` if you're not sure)

2.15.1

### Shell

Git Bash

### What language and version are you using in your application?

ruby 3.0.2p107

**Comment by amcaplan** [comment]
@karreiro We keep seeing this error. While I'm not an expert in the affected code, I assume something in here is most likely to be the cause: https://github.com/Shopify/shopify-cli/blob/9acc06d13a8be760ac2798bbea71211222cba5f2/lib/shopify_cli/theme/development_theme.rb#L33-L41

Unfortunately we're not surfacing the real error due to `theme.shop` here: https://github.com/Shopify/shopify-cli/blob/9acc06d13a8be760ac2798bbea71211222cba5f2/lib/shopify_cli/theme/dev_server.rb#L95

1. `theme&.shop`
2. Even that won't be sufficient, because the point is that `theme` is `nil` and that's not supposed to happen. Is there another error message that would apply reliably to this situation? I assume it's to do with [this](https://github.com/Shopify/shopify-cli/blob/9acc06d13a8be760ac2798bbea71211222cba5f2/lib/shopify_cli/theme/theme.rb#L105-L119) but hard for me to know without much more context.
3. If we can't say reliably what's happened, should we just add a line which will re-raise the original error, giving us more details and opportunity to fix:
```ruby
raise unless theme
```

**Comment by karreiro** [comment]
Thank you for the initial investigation, @amcaplan! I will keep those points in mind :)

**Comment by Victor-Jacon** [comment]
Hey friend. I have a fix that worked for me. (after 4h~6h trying..)

On your browser:
1-login to your shopify partner account 
(https://www.shopify.com/partners)

2-create a staff account with a diferent email. 
  a-login to https://partners.shopify.com
  b-on your left sidebar click on staff (its the second option bottom to top)
  c-click on invite staff and put your second email here. yeah, youre gonna have 2 accounts for you. 
  d-give yourself all permissions by clicking on all checkboxes
  
On your browser (invite yourself again to work on your shop)
1-Navigate to your store URL: yourstore.myshopify.com/admin
2-Navigate to https://yourstore.myshopify.com/admin/settings/account
3-On the left sidebar, click on users and permissions (the 4th option top to bottom)
4-Invite your own staff account again.

On your browser (write down your shop password. you will need it later)
1-Navigate to https://yourstore.myshopify.com/admin/online_store/preferences
2-Navigate all the way down, write down the password it shows on the section "password protection"

Run on your terminal, inside the shopify project's folder:
shopify logout

On your browser:
logout from shopify partners
logout from shopify store

Then..

On your browser:
1-navigate to yourstore.myshopify.com + login to your STAFF ACCOUNT (the second email, not your shopify partner account)

On your terminal:
shopify login --store yourstore.myshopify.com
shopify theme serve
it should open a chrome window saying : you are authenticated, you can now close this window. (something like that)

On your browser:
a-go to http://127.0.0.1:9292/
b-it should prompt you to put your store password.
c-you should be able to see your local changes now <3

If it helped you, please consider giving it a thumbs up, so others can benefit from this solution, and not waste 4h-6h solving it from scratch as I had to.

**Comment by idemmanuel001** [comment]
> Hey friend. I have a fix that worked for me. (after 4h~6h trying..)
> 
> On your browser: 1-login to your shopify partner account (https://www.shopify.com/partners)
> 
> 2-create a staff account with a diferent email. a-login to https://partners.shopify.com b-on your left sidebar click on staff (its the second option bottom to top) c-click on invite staff and put your second email here. yeah, youre gonna have 2 accounts for you. d-give yourself all permissions by clicking on all checkboxes
> 
> On your browser (invite yourself again to work on your shop) 1-Navigate to your store URL: yourstore.myshopify.com/admin 2-Navigate to https://yourstore.myshopify.com/admin/settings/account 3-On the left sidebar, click on users and permissions (the 4th option top to bottom) 4-Invite your own staff account again.
> 
> On your browser (write down your shop password. you will need it later) 1-Navigate to https://yourstore.myshopify.com/admin/online_store/preferences 2-Navigate all the way down, write down the password it shows on the section "password protection"
> 
> Run on your terminal, inside the shopify project's folder: shopify logout
> 
> On your browser: logout from shopify partners logout from shopify store
> 
> Then..
> 
> On your browser: 1-navigate to yourstore.myshopify.com + login to your STAFF ACCOUNT (the second email, not your shopify partner account)
> 
> On your terminal: shopify login --store yourstore.myshopify.com shopify theme serve it should open a chrome window saying : you are authenticated, you can now close this window. (something like that)
> 
> On your browser: a-go to http://127.0.0.1:9292/ b-it should prompt you to put your store password. c-you should be able to see your local changes now <3
> 
> If it helped you, please consider giving it a thumbs up, so others can benefit from this solution, and not waste 4h-6h solving it from scratch as I had to.

I am going to try this out, I hope it works for me.
Thanks to you and everyone who tried to help.
