### ISSUE TITLE
SystemExit: abnormal termination status: 1

### ISSUE THREAD

**Issue by findoc2021** [Shopify/shopify-cli#2204]
%23 Issue summary

Write a short description of the issue here ↓

%23%23 Expected behavior

What do you think should happen%3F

%23%23 Actual behavior

What actually happens%3F

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

%23%23 Steps to reproduce the problem

1.
1.
1.

%23%23 Stacktrace

C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/theme-check-1.9.2/lib/theme_check/cli.rb:105:in `abort'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/theme-check-1.9.2/lib/theme_check/cli.rb:105:in `rescue in parse'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/theme-check-1.9.2/lib/theme_check/cli.rb:102:in `parse'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.10.0/lib/project_types/theme/commands/check.rb:14:in `parse'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.10.0/lib/shopify_cli/command/sub_command.rb:10:in `call'

%23%23 Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by gonzaloriestra** [comment]
Hi! Sorry for the late response, but we would need more details to be able to investigate it.

Could you specify what you were trying to run? I noticed you are running an old version of the CLI, could you try to upgrade and try again?

Thanks!
