### ISSUE TITLE
[Bug]: msgpack.rb:7:in `require': incompatible library version

### ISSUE THREAD

**Issue by justinhenricks** [Shopify/shopify-cli#2301]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

Shopify app serve should run the server

### Actual behavior

Getting error that msgpack.rb:7:in `require': incompatible library version

### Stack trace

```shell
┃ /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/msgpack-1.5.1/lib/msgpack.rb:7:in `require': incompatible library version - /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/msgpack-1.5.1/lib/msgpack/msgpack.bundle (LoadError)
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/msgpack-1.5.1/lib/msgpack.rb:7:in `<top (required)>'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `require'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `block in <top (required)>'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/explicit_require.rb:45:in `rescue in with_gems'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/explicit_require.rb:41:in `with_gems'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `<top (required)>'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache.rb:54:in `require_relative'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache.rb:54:in `<top (required)>'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap.rb:5:in `require_relative'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap.rb:5:in `<top (required)>'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/setup.rb:3:in `require_relative'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/setup.rb:3:in `<top (required)>'
┃ 	from /Users/justin/Workspace/SCP/Shopify/apps/test_rails_app/config/boot.rb:4:in `require'
┃ 	from /Users/justin/Workspace/SCP/Shopify/apps/test_rails_app/config/boot.rb:4:in `<top (required)>'
┃ 	from bin/rails:3:in `require_relative'
┃ 	from bin/rails:3:in `<main>'
┃ /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/msgpack-1.5.1/lib/msgpack.rb:7:in `require': incompatible library version - /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/msgpack-1.5.1/lib/msgpack/msgpack.bundle (LoadError)
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/msgpack-1.5.1/lib/msgpack.rb:7:in `<top (required)>'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `require'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `block in <top (required)>'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/explicit_require.rb:42:in `with_gems'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/store.rb:5:in `<top (required)>'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache.rb:54:in `require_relative'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache.rb:54:in `<top (required)>'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap.rb:5:in `require_relative'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap.rb:5:in `<top (required)>'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/setup.rb:3:in `require_relative'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/bootsnap-1.11.1/lib/bootsnap/setup.rb:3:in `<top (required)>'
┃ 	from /Users/justin/Workspace/SCP/Shopify/apps/test_rails_app/config/boot.rb:4:in `require'
┃ 	from /Users/justin/Workspace/SCP/Shopify/apps/test_rails_app/config/boot.rb:4:in `<top (required)>'
┃ 	from bin/rails:3:in `require_relative'
┃ 	from bin/rails:3:in `<main>'
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### Reproduction steps

1. Create new rails app: shopify app create rails
2. Install correct version of ruby for project: rbenv install 3.1.2 
3. bundle install
4. shopify app serve

### Operating System

Mac OS Monterey 12.3.1

### CLI version (run `shopify version` if you're not sure)

2.16.1

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

3.1.2p20

### What language and version are you using in your application?

Ruby

**Comment by justinhenricks** [comment]
Ah thank you!

Justin Henricks
***@***.***
(518) 423-3651

**Comment by pepicrft** [comment]
Did it work? 😛

**Comment by justinhenricks** [comment]
I’ve started working on a node project and the CLI I have is working perfectly with that so I don’t want to mess anything up at the moment. But what you said makes sense! Will do it if I come back to trying to build a rails project. 

Justin Henricks
***@***.***
(518) 423-3651

**Comment by pepicrft** [comment]
Sounds good! I'll close the issue then. If you come across any other issue or this one persists, feel free to create a new issue. I'll gladly help you with it.
