### ISSUE TITLE
[Bug]: Net::OpenTimeout: Net::OpenTimeout

### ISSUE THREAD

**Issue by seymoe** [Shopify/shopify-cli#2361]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

shopify login

### Actual behavior

it didnot work

### Stack trace

```shell
/usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/protocol.rb:43:in `ssl_socket_connect'
/usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:1048:in `connect'
/usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
/usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:965:in `start'
/usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:1530:in `request'
```

### Reproduction steps

1.  brew install shopify-cli
2. SHOPIFY_CLI_STACKTRACE=1 shopify app tunnel auth MYTOKEN
3. shopify login

### Operating System

x86_64-darwin19

### CLI version (run `shopify version` if you're not sure)

2.17.0

### Shell

/bin/zsh

### Ruby version (run `ruby -v` if you're not sure)

3.1.2p20

### What language and version are you using in your application?

Node

**Comment by seymoe** [comment]
SHOPIFY_CLI_STACKTRACE=1 shopify login
✓ Initiating authentication
✗ An unexpected error occured.
	To submit an issue include the stack trace.

/usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/protocol.rb:43:in `ssl_socket_connect': Net::OpenTimeout (Net::OpenTimeout)
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:1048:in `connect'
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:965:in `start'
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:1530:in `request'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/identity_auth.rb:274:in `post_request'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/identity_auth.rb:263:in `post_token_request'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/identity_auth.rb:182:in `request_access_token'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/identity_auth.rb:67:in `authenticate'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/commands/login.rb:33:in `call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/command.rb:35:in `call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/executor.rb:15:in `call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/monorail.rb:26:in `log'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/bin/shopify:49:in `block in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/bin/shopify:59:in `<top (required)>'
	from /usr/local/bin/shopify:8:in `load'
	from /usr/local/bin/shopify:8:in `<main>'
➜  ~ SHOPIFY_CLI_STACKTRACE=1 shopify login
✓ Initiating authentication
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✗ Timed out while waiting for response from Shopify
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
➜  ~ SHOPIFY_CLI_STACKTRACE=1 shopify login
✓ Initiating authentication
✗ An unexpected error occured.
	To submit an issue include the stack trace.

/usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/protocol.rb:43:in `ssl_socket_connect': Net::OpenTimeout (Net::OpenTimeout)
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:1048:in `connect'
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:965:in `start'
	from /usr/local/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:1530:in `request'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/identity_auth.rb:274:in `post_request'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/identity_auth.rb:263:in `post_token_request'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/identity_auth.rb:182:in `request_access_token'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/identity_auth.rb:67:in `authenticate'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/commands/login.rb:33:in `call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/command.rb:35:in `call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/executor.rb:15:in `call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/monorail.rb:26:in `log'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/bin/shopify:49:in `block in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.17.0/gems/shopify-cli-2.17.0/bin/shopify:59:in `<top (required)>'
	from /usr/local/bin/shopify:8:in `load'
	from /usr/local/bin/shopify:8:in `<main>'
