### ISSUE TITLE
can't find gem shopify-cli (>= 0.a) with executable shopify (Gem::GemNotFoundException)

### ISSUE THREAD

**Issue by imxinz** [Shopify/shopify-cli#2403]
[root@xinz-host-01 ~]# ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]

[root@xinz-host-01 ~]# rvm list
   ruby-2.6.0 [ x86_64 ]
=* ruby-3.0.2 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

[root@xinz-host-01 ~]# shopify version
/usr/local/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems.rb:281:in `find_spec_for_exe': can't find gem shopify-cli (>= 0.a) with executable shopify (Gem::GemNotFoundException)
	from /usr/local/rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems.rb:300:in `activate_bin_path'
	from /usr/local/bin/shopify:23:in `<main>'

**Comment by amcaplan** [comment]
Hi @imxinz, thanks for opening up an issue.

I did see that a similar issue was [resolved](https://stackoverflow.com/a/62769239) with `rvm reset`, so it's worth a try.

Perhaps you can share the output of `gem env`? That might help understand what's going on when you encounter this error.
