### ISSUE TITLE
[Bug]: Errno::EACCES: Permission denied - bind(2) for 0.0.0.0:3456

### ISSUE THREAD

**Issue by aivalabs** [Shopify/shopify-cli#2423]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

It should have worked

### Actual behavior

It did not work

### Stack trace

```shell
C:/Ruby27-x64/lib/ruby/2.7.0/socket.rb:201:in `bind'
C:/Ruby27-x64/lib/ruby/2.7.0/socket.rb:201:in `listen'
C:/Ruby27-x64/lib/ruby/2.7.0/socket.rb:765:in `block in tcp_server_sockets'
C:/Ruby27-x64/lib/ruby/2.7.0/socket.rb:227:in `each'
C:/Ruby27-x64/lib/ruby/2.7.0/socket.rb:227:in `foreach'
```

### Reproduction steps

1.
2.
3.

### Operating System

x64-mingw32

### CLI version (run `shopify version` if you're not sure)

2.18.0

### Ruby version (run `ruby -v` if you're not sure)

2.7.6p219

**Comment by amcaplan** [comment]
Hi @aivalabs, thanks for opening an issue. I'm not really sure what you were doing or how it went wrong; could you please provide more details so we can help diagnose and fix?

**Comment by amcaplan** [comment]
Hi @bstarr322, it looks like you have another running process on that port. Can you please check what it is? Something like `netstat -aof | findstr :3456` should do it.

**Comment by x7Michi10x** [comment]
I am facing the same issue when using "shopify login" command. Netstat does not show any processes which are blocking the port ...

**CLI version:** 2.26.0
**Ruby version:** 3.1.2p20

**Stacktrace:**
D:/Tools/Ruby31-x64/lib/ruby/3.1.0/socket.rb:201:in `bind': Permission denied - bind(2) for 0.0.0.0:3456 (Errno::EACCES)        from D:/Tools/Ruby31-x64/lib/ruby/3.1.0/socket.rb:201:in `listen'
        from D:/Tools/Ruby31-x64/lib/ruby/3.1.0/socket.rb:765:in `block in tcp_server_sockets'
        from D:/Tools/Ruby31-x64/lib/ruby/3.1.0/socket.rb:227:in `each'
        from D:/Tools/Ruby31-x64/lib/ruby/3.1.0/socket.rb:227:in `foreach'
        from D:/Tools/Ruby31-x64/lib/ruby/3.1.0/socket.rb:763:in `tcp_server_sockets'
        from D:/Tools/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.26.0/vendor/deps/webrick/lib/webrick/utils.rb:60:in `create_listeners'
        from D:/Tools/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.26.0/vendor/deps/webrick/lib/webrick/server.rb:130:in `listen'
        from D:/Tools/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.26.0/vendor/deps/webrick/lib/webrick/server.rb:111:in `initialize'
        from D:/Tools/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.26.0/vendor/deps/webrick/lib/webrick/httpserver.rb:47:in `initialize'
        from D:/Tools/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.26.0/lib/shopify_cli/identity_auth.rb:137:in `new'
        from D:/Tools/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.26.0/lib/shopify_cli/identity_auth.rb:137:in `server'
        from D:/Tools/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.26.0/lib/shopify_cli/identity_auth.rb:155:in `block in initiate_authentication'

**Comment by ddomdel** [comment]
having the exact same issue
