### ISSUE TITLE
SocketError: Failed to open TCP connection to accounts.shopify.com:443 (getaddrinfo: nodename nor servname provided, or not known)

### ISSUE THREAD

**Issue by adamrasheed** [Shopify/shopify-cli#2438]
# Issue summary

Write a short description of the issue here ↓
Whenever I run `shopify login` and authenticate successfully through the browser, I get the following error:
```
✗ An unexpected error occured.
	To submit an issue include the stack trace.
	To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.
```

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Stacktrace

/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/net/http.rb:987:in `initialize'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/net/http.rb:987:in `open'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/net/http.rb:987:in `block in connect'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
/usr/local/Cellar/ruby/3.0.3/lib/ruby/3.0.0/timeout.rb:107:in `timeout'

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by absolutbly** [comment]
@adamrasheed Did you get this problem solved?  I have the same issue as you

**Comment by FazalJarral** [comment]
Facing the same issue, were you able to solve it?
