### ISSUE TITLE
Theme check failed with error after recent CLI Upgrade

### ISSUE THREAD

**Issue by devdarren7** [Shopify/shopify-cli#2486]
### **Seems to log all errors to console , but throws this error upon supposed completion :**
**Shopify CLI version : 2.20.1**

```
250 files inspected, 21 offenses detected, 15 offenses auto-correctable
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Theme check failed with error:
┃ C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/theme-check-1.10.3/lib/theme_check/cli.rb:197:in `check': ThemeCheck::Cli::Abort
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/theme-check-1.10.3/lib/theme_check/cli.rb:123:in `run!'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/lib/project_types/theme/commands/check.rb:27:in `call'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/lib/shopify_cli/command/sub_command.rb:16:in `call'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/lib/shopify_cli/command.rb:27:in `call'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/lib/shopify_cli/core/executor.rb:16:in `block in call'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/lib/shopify_cli/core/executor.rb:15:in `call'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/lib/shopify_cli/core/monorail.rb:26:in `log'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/lib/shopify_cli/core/entry_point.rb:23:in `call'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/bin/shopify:50:in `block (2 levels) in <top (required)>'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/bin/shopify:49:in `block in <top (required)>'
┃       from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/bin/shopify:59:in `<top (required)>'
┃       from C:/Ruby30-x64/bin/shopify:23:in `load'
┃       from C:/Ruby30-x64/bin/shopify:23:in `<main>'
```

**Comment by benopop** [comment]
I'm also getting a similar issue but I'm on Catalina 10.15.7

**Comment by ashok-mobi** [comment]
I'm also getting same issue.
