### ISSUE TITLE
[Bug]: Shopify CLI not allowing login for authentication

### ISSUE THREAD

**Issue by DavidFrempong** [Shopify/shopify-cli#2499]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Expected CLI to authenticate login to Shopify.

### Actual behavior

Ran the command "shopify login [--store storename.myshopify.com]". Response is "Initiating authentication", followed by the browser opening the Shopify CLI login page. Once an account is chosen to log in with, the page crashes and this message in the terminal is returned: 

✗ An unexpected error occured.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

** [Bugsnag] 2260-06-03 11:48:56 -0400: Unable to send information to Bugsnag (https://notify.bugsnag.com), #<Net::OpenTimeout: execution expired>
** [Bugsnag] 2260-06-03 11:48:56 -0400: ["/usr/lib/ruby/2.7.0/net/http.rb:960:in `initialize'", "/usr/lib/ruby/2.7.0/net/http.rb:960:in `open'", "/usr/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'", "/usr/lib/ruby/2.7.0/timeout.rb:105:in `timeout'", "/usr/lib/ruby/2.7.0/net/http.rb:958:in `connect'", "/usr/lib/ruby/2.7.0/net/http.rb:943:in `do_start'", "/usr/lib/ruby/2.7.0/net/http.rb:932:in `start'", "/usr/lib/ruby/2.7.0/net/http.rb:1483:in `request'", "/var/lib/gems/2.7.0/gems/bugsnag-6.24.2/lib/bugsnag/delivery/synchronous.rb:51:in `request'", "/var/lib/gems/2.7.0/gems/bugsnag-6.24.2/lib/bugsnag/delivery/synchronous.rb:12:in `deliver'", "/var/lib/gems/2.7.0/gems/bugsnag-6.24.2/lib/bugsnag/delivery/thread_queue.rb:38:in `block in serialize_and_deliver'", "/var/lib/gems/2.7.0/gems/bugsnag-6.24.2/lib/bugsnag/delivery/thread_queue.rb:55:in `block (2 levels) in start_once!'"]

### Reproduction steps

1. Ran the command **shopify login [--store storename.myshopify.com]**.
2. Response: **Initiating authentication**, followed by the browser opening the Shopify CLI login page. 
3. Once an account is chosen to log in with, the page crashes and the failure message in the terminal is returned.

### Operating System

Ubuntu 20.04

### CLI version (run `shopify version` if you're not sure)

2.20.0

**Comment by DavidFrempong** [comment]
Discovered Apache server was not running which was causing the issue. Note to other Shopify developers - make sure your Apache server is running, otherwise the Shopify CLI will not connect.
