### ISSUE TITLE
[Bug]: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)

### ISSUE THREAD

**Issue by darshikaGilder30** [Shopify/shopify-cli#2509]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

It should login properly so I can move forward another steps to create APP.

### Actual behavior

When I try to login shopify using CLI it'll show this type of error.

### Stack trace

```shell
/usr/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock'
/usr/lib/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/lib/ruby/2.7.0/net/http.rb:1009:in `connect'
/usr/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
/usr/lib/ruby/2.7.0/net/http.rb:932:in `start'
```

### Reproduction steps

1.
2.
3.

### Operating System

x86_64-linux-gnu

### CLI version (run `shopify version` if you're not sure)

2.20.1

### Shell

/bin/bash

### Ruby version (run `ruby -v` if you're not sure)

2.7.0p0

**Comment by isaacroldan** [comment]
Hi @darshikaGilder30, thank you for reporting this issue.
To better understand what could be happening, could you run the same command adding the `DEBUG` env var? like:
`DEBUG=1 shopify login`

And post the results here? (don't forget to remove any sensitive information from the log)
