### ISSUE TITLE
[Bug]: Serve Command Not Accepting Flags

### ISSUE THREAD

**Issue by avcohen** [Shopify/shopify-cli#2574]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Shopify CLI [Documentation](https://shopify.dev/themes/tools/cli/theme-commands#serve) notes that `--theme < NAME_OR_ID>` is a valid parameter. 

I would expect the cli parses the flag.

### Actual behavior

Flag is noted by the error logger that `invalid option: --theme (OptionParser::InvalidOption)`

### Stack trace

```shell
✗ An unexpected error occured.
	To submit an issue include the stack trace.

/opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/lib/shopify_cli/options.rb:28:in `parse_flags': invalid option: --theme (OptionParser::InvalidOption)
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/lib/shopify_cli/options.rb:19:in `parse'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/lib/shopify_cli/command/sub_command.rb:10:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/lib/shopify_cli/command.rb:24:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/lib/shopify_cli/core/executor.rb:16:in `block in call'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/lib/shopify_cli/core/executor.rb:15:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/lib/shopify_cli/core/monorail.rb:30:in `log'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/lib/shopify_cli/core/entry_point.rb:23:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/bin/shopify:37:in `block (2 levels) in <top (required)>'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/bin/shopify:36:in `block in <top (required)>'
	from /opt/homebrew/Cellar/shopify-cli/2.7.2/gems/shopify-cli-2.7.2/bin/shopify:47:in `<top (required)>'
	from /opt/homebrew/bin/shopify:6:in `load'
	from /opt/homebrew/bin/shopify:6:in `<main>'
```

### Reproduction steps

1. Run `shopify theme serve --theme development`
2. Error is logged to console

### Operating System

M1 Pro - Mac OS Monterrey

### CLI version (run `shopify version` if you're not sure)

2.7.2

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]

**Comment by jessetuglu** [comment]
Hi @avcohen, thanks for raising this. What's the output of running `shopify version`?

**Comment by avcohen** [comment]
@jessetuglu — No worries.

I went back through the setup instructions after uninstalling via homebrew and I do in fact now have the correct version — `2.23.0` and the `--theme` flag is working.

It's possible I skipped the Ruby step — `gem install shopify-cli`

Apologies for the false alarm. Thanks for the quick response, your message helped me located my mistep.

Cheers

**Comment by jessetuglu** [comment]
All good! Glad I could help 🙏.
