### ISSUE TITLE
[Bug]: <YOUR ISSUE TITLE>

### ISSUE THREAD

**Issue by ekwoka** [Shopify/shopify-cli#2578]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

When no internet, just fail gracefully

### Actual behavior

When running any command (specifically `shopify switch`) the script crashes but Ruby never closes, continuing to burn up a core at 98% until the process is killed. Subsequent attemps and fails will add more ruby processes consuming more cores.
<img width="294" alt="Screen Shot 2022-08-24 at 9 55 27 PM" src="https://user-images.githubusercontent.com/43540491/186489744-88dfbdb2-6eb4-433e-9948-a31387ff4eaa.png">

### Reproduction steps

1. Have No internet.
2. Run `shopify switch` a few times.
3. Cook some eggs.

### Operating System

Mac OS 12.5.1

### CLI version (run `shopify version` if you're not sure)

2.23.0

### Shell

Bash

### Ruby version (run `ruby -v` if you're not sure)

2.6.8p205

**Comment by amcaplan** [comment]
Hi @ekwoka, I'd love to try and help, but I installed the same gem version using the same ruby version and OS, and I don't see the same issue at all. After running `shopify switch` several times with internet disconnected, I don't see any aggregation of Ruby processes.

When the process dies, I see an error like

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': Failed to open TCP connection to ariel-caplan-test-alternate.myshopify.com:443 (getaddrinfo: nodename nor servname provided, or not known) (SocketError)
```

Do you see an error? Does the process just hang? Does it return control to you in the terminal?

**Comment by amcaplan** [comment]
Hi @ekwoka, I'd love to try and help, but I installed the same gem version using the same ruby version and OS, and I don't see the same issue at all. After running `shopify switch` several times with internet disconnected, I don't see any aggregation of Ruby processes.

When the process dies, I see an error like

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': Failed to open TCP connection to ariel-caplan-test-alternate.myshopify.com:443 (getaddrinfo: nodename nor servname provided, or not known) (SocketError)
```

Do you see an error? Does the process just hang? Does it return control to you in the terminal?

**Comment by amcaplan** [comment]
Hi @ekwoka, I'd love to try and help, but I installed the same gem version using the same ruby version and OS, and I don't see the same issue at all. After running `shopify switch` several times with internet disconnected, I don't see any aggregation of Ruby processes.

When the process dies, I see an error like

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': Failed to open TCP connection to XXXXXXXXXXX.myshopify.com:443 (getaddrinfo: nodename nor servname provided, or not known) (SocketError)
```

Do you see an error? Does the process just hang? Does it return control to you in the terminal?
