### ISSUE TITLE
[Bug]: Ruby31-x64/lib/ruby/3.1.0/open3.rb:222:in `spawn': No such file or directory - ruby

### ISSUE THREAD

**Issue by nielsrobin** [Shopify/shopify-cli#2604]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

That I get the version of shopify-cli.

### Actual behavior

System fails.

### Stack trace

```shell
C:\WINDOWS\system32>shopify version
X An unexpected error occured.
        To submit an issue include the stack trace.

E:/Ruby31-x64/lib/ruby/3.1.0/open3.rb:222:in `spawn': No such file or directory - ruby (Errno::ENOENT)
        from E:/Ruby31-x64/lib/ruby/3.1.0/open3.rb:222:in `popen_run'
        from E:/Ruby31-x64/lib/ruby/3.1.0/open3.rb:210:in `popen2e'
        from E:/Ruby31-x64/lib/ruby/3.1.0/open3.rb:399:in `capture2e'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:199:in `delegate_open3'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:68:in `capture2e'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/lib/shopify_cli/context.rb:538:in `capture2e'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/lib/shopify_cli/environment.rb:15:in `ruby_version'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/lib/shopify_cli/command.rb:89:in `check_ruby_version'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/lib/shopify_cli/command.rb:32:in `call'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/lib/shopify_cli/core/executor.rb:15:in `call'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/lib/shopify_cli/core/entry_point.rb:38:in `block in call'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/lib/shopify_cli/core/monorail.rb:26:in `log'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/lib/shopify_cli/core/entry_point.rb:37:in `call'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/bin/shopify:49:in `block in <top (required)>'
        from E:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.24.0/bin/shopify:59:in `<top (required)>'
        from e:/Ruby31-x64/bin/shopify:32:in `load'
        from e:/Ruby31-x64/bin/shopify:32:in `<main>'

C:\WINDOWS\system32>git version
git version 2.37.3.windows.1

C:\WINDOWS\system32>ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt]

C:\WINDOWS\system32>node -v
v14.15.0
```

### Reproduction steps

followed this guide: https://shopify.dev/themes/tools/cli/installation
1. installed [Ruby+Devkit 3.1.2-1 (x64)](https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.1.2-1/rubyinstaller-devkit-3.1.2-1-x64.exe)
2. ran "gem install shopify-cli"
3. typed "shopify version"

### Operating System

Windows 10 Home

### CLI version (run `shopify version` if you're not sure)

2.24.0

### Shell

CMD

### Ruby version (run `ruby -v` if you're not sure)

3.1.2p20 

### What language and version are you using in your application?

Ruby 3.1.2p20, Node v14.15.0

**Comment by memetican** [comment]
Having what appears to be an identical issue when I run `shopify` or `shopify version`.  

```
d:/Ruby31-x64/lib/ruby/3.1.0/open3.rb:222:in `spawn': No such file or directory - ruby (Errno::ENOENT)
        from d:/Ruby31-x64/lib/ruby/3.1.0/open3.rb:222:in `popen_run'
```

ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt]

node -v
v16.9.1

git -v
git version 2.37.3.windows.1

I've reinstalled each piece, restarted several times with no luck.
I think I'll try adding the 32-bit version of ruby to see if anything fixes.
