### ISSUE TITLE
[Bug]: Errno::EPERM: Operation not permitted - ./Library/Accounts

### ISSUE THREAD

**Issue by jakobmcdonald** [Shopify/shopify-cli#2652]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

pulled theme

### Actual behavior

did not pull theme. received "An unexpected error occured.

### Stack trace

```shell
<internal:dir>:220:in `glob'
/opt/homebrew/Cellar/shopify-cli/2.26.0/gems/shopify-cli-2.26.0/lib/shopify_cli/theme/root.rb:29:in `glob'
/opt/homebrew/Cellar/shopify-cli/2.26.0/gems/shopify-cli-2.26.0/lib/shopify_cli/theme/root.rb:29:in `glob'
/opt/homebrew/Cellar/shopify-cli/2.26.0/gems/shopify-cli-2.26.0/lib/shopify_cli/theme/theme.rb:24:in `theme_files'
/opt/homebrew/Cellar/shopify-cli/2.26.0/gems/shopify-cli-2.26.0/lib/shopify_cli/theme/syncer.rb:207:in `download_theme!'
```

### Reproduction steps

1. logged into shopify account in cli
2.logged into store
3. used $ shopify theme pull
4. selected theme to pull
5. received error

### Operating System

arm64-darwin21

### CLI version (run `shopify version` if you're not sure)

2.26.0

### Shell

/bin/zsh

### Ruby version (run `ruby -v` if you're not sure)

3.1.2p20

**Comment by amcaplan** [comment]
Hi @jakobmcdonald, thanks for getting in touch!

It seems you're trying to pull a theme while in your user home directory. However, `theme pull` is designed to be used from within a directory which you've designated for your theme. (In git terms, it's more similar to `git pull` than `git clone`.) 
Currently, it's attempting to check for theme files in the current directory, and ends up looking in places it shouldn't, hence the observed permissions issues.

I'd recommend making a new subdirectory and running `shopify theme pull` from there. Something like:

```sh
$ mkdir mytheme
$ cd mytheme
$ shopify theme pull
```

Please confirm this works for you.

**Comment by Esha98** [comment]
✅ I concur with @amcaplan's proposed solution of creating a folder first using `mkdir folder-name` and then pulling the theme into that folder using `cd folder-name` followed by `shopify theme pull`. 

Generated the same issue and was able to successfully resolve using this method.

**Comment by amcaplan** [comment]
Thanks for the confirmation @Esha98!

I'm going to close this as it's been solved for some time.
