### ISSUE TITLE
[Bug]: Net::OpenTimeout: Failed to open TCP connection to accounts.shopify.com:443 (Operation timed out - user specified timeout)

### ISSUE THREAD

**Issue by ahaShop** [Shopify/shopify-cli#2662]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

sign out

### Actual behavior

returned an error

### Stack trace

```shell
/opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:1001:in `rescue in connect'
/opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:997:in `connect'
/opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
/opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:965:in `start'
/opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/net/http.rb:1530:in `request'
```

### Reproduction steps

1.Shopify logout
2.
![image](https://user-images.githubusercontent.com/114213193/196367058-91773141-f2c0-4dd6-8555-d8ec106869d5.png)

3.
![image](https://user-images.githubusercontent.com/114213193/196367280-ef6d13cf-029c-41f8-bb83-58666ed55307.png)

### Operating System

Mac

### CLI version (run `shopify version` if you're not sure)

2.28.0

### Shell

/bin/zsh

### Ruby version (run `ruby -v` if you're not sure)

2.6.8p205

**Comment by chenjiapenggeorge** [comment]
Hi, have you solved this problem? I have the same problem as you
