### ISSUE TITLE
[Bug]: JSON::ParserError: unexpected token at ''

### ISSUE THREAD

**Issue by inglemirepharm** [Shopify/shopify-cli#2754]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

good running

### Actual behavior

╭─ success ───────────────────────────────────────────────╮
│                                                         │
│  Preview your theme                                     │
│    • http://127.0.0.1:9292                              │
│                                                         │
│  Next steps                                             │
│    • Customize your theme at the theme editor           │
│    • Share your theme preview                           │
│                                                         │
╰─────────────────────────────────────────────────────────╯

✗ An unexpected error occurred.
        To submit an issue include the stack trace.

### Stack trace

```shell
/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/json/common.rb:216:in `parse'
/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/json/common.rb:216:in `parse'
/usr/local/lib/node_modules/@shopify/theme/node_modules/_@shopify_cli-kit@3.46.0@@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/api.rb:70:in `block in request'
/usr/local/lib/node_modules/@shopify/theme/node_modules/_@shopify_cli-kit@3.46.0@@shopify/cli-kit/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
/usr/local/lib/node_modules/@shopify/theme/node_modules/_@shopify_cli-kit@3.46.0@@shopify/cli-kit/assets/cli-ruby/lib/shopify_cli/api.rb:89:in `request'
```

### Reproduction steps

1.shopify theme dev
2.
3.

### Operating System

x86_64-darwin21

### CLI version (run `shopify version` if you're not sure)

3.46.0

### Shell

/bin/bash

### Ruby version (run `ruby -v` if you're not sure)

3.2.2p53

**Comment by karreiro** [comment]
Hi @inglemirepharm,

Could you share sharing the `request_id` with me? This information will help me to gather additional details about the issue you're facing.

To obtain the `request_id`, you can append the `--verbose` flag to your command.

Thank you for reporting this.
