### ISSUE TITLE
shopify create lists disabled organizations

### ISSUE THREAD

**Issue by duleorlovic** [Shopify/shopify-cli#639]
# Issue summary

When I use `shopify create` , when it asks for organization to choose, it lists disabled organizations. 
I had three organizations but I asked Shopify stuff to disable two so I end up using only the first organization that I created. When shopify app cli asks me for organization, it lists only those two disabled ogranizations, for example
```
? Select organization (Choose with ↑ ↓ ⏎, filter with 'f')                                          
> 1. TRK Innovations
  2. TRK INNOVATIONS
```

## Expected behavior

It should ask only for one active organization.

## Actual behavior

It asks me to choose from two disabled organizations.
At the end of output, there is a error in ruby and 404 page from Shopify

<details>

```
┏━━ Running migrations… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ == 20200603055628 CreateShops: migrating ======================================
┃ -- create_table(:shops)
┃    -> 0.0019s
┃ -- add_index(:shops, :shopify_domain, {:unique=>true})
┃    -> 0.0014s
┃ == 20200603055628 CreateShops: migrated (0.0033s) =============================
┃ 
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (3.51s) ━━
This command ran with ID: 77571
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	33: from /home/orlovic/.shopify-app-cli/bin/shopify:36:in `<main>'
	32: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	31: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	30: from /home/orlovic/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	29: from /home/orlovic/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:18:in `call'
	28: from /home/orlovic/.shopify-app-cli/lib/shopify-cli/core/monorail.rb:20:in `log'
	27: from /home/orlovic/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:19:in `block in call'
	26: from /home/orlovic/.shopify-app-cli/lib/shopify-cli/core/executor.rb:17:in `call'
	25: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	24: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	23: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	22: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	21: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:53:in `twrap'
	20: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	19: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	18: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	17: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	16: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	15: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	14: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	13: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	12: from /home/orlovic/.shopify-app-cli/lib/shopify-cli/commands/create.rb:8:in `call'
	11: from /home/orlovic/.shopify-app-cli/lib/shopify-cli/command.rb:17:in `call'
	10: from /home/orlovic/.shopify-app-cli/lib/shopify-cli/sub_command.rb:11:in `call'
	 9: from /home/orlovic/.shopify-app-cli/lib/project_types/rails/commands/create.rb:43:in `call'
	 8: from /home/orlovic/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
	 7: from /home/orlovic/.shopify-app-cli/lib/shopify-cli/tasks/create_api_client.rb:9:in `call'
	 6: from /home/orlovic/.shopify-app-cli/lib/shopify-cli/partners_api.rb:48:in `query'
	 5: from /home/orlovic/.shopify-app-cli/lib/shopify-cli/partners_api.rb:56:in `authenticated_req'
	 4: from /home/orlovic/.shopify-app-cli/lib/shopify-cli/partners_api.rb:49:in `block in query'
	 3: from /home/orlovic/.shopify-app-cli/lib/shopify-cli/api.rb:27:in `query'
	 2: from /home/orlovic/.shopify-app-cli/lib/shopify-cli/api.rb:76:in `request'
	 1: from /home/orlovic/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
/home/orlovic/.shopify-app-cli/lib/shopify-cli/api.rb:72:in `block in request': 500 (ShopifyCli::API::APIRequestServerError)
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Something went wrong.</title>
  <style type="text/css">

    * { border:0; margin:0; padding:0; -moz-box-sizing:border-box; -webkit-box-sizing:border-box; box-sizing:border-box; }
    html,body { height:100%; border:0; margin:0; padding:0; font-family:"Helvetica Neue", Helvetica, Arial, sans-serif; font-weight:300; background:#fff; }
    body { min-height:100%; font-size:16px; line-height:22px; color:#6c6c6c; }
    a { color:#479ccf; }

    h1,h2,h3,h4,h5,h6 { text-align:left; margin:0 0 20px 0; color:#31373D; font-weight:700; }
    h1 { font-size:28px; line-height:48px; margin-bottom:7px; }
    h2 { font-size:20px; font-weight:300; line-height:30px; color:#6c6c6c; }
    h3 { font-size:17px; line-height:30px; position:relative; padding-bottom:18px; margin-bottom:22px; font-weight:400; }
    h3:after { content:""; position:absolute; left:0; bottom:0; height:2px; width:76px; background:#EAEAEA; }
    h4 { font-size:14px; margin-bottom:3px; }

    img { max-width:100%; }

    .ico { display:inline-block; }
    .ico svg { background-size:contain; background-position:center; width:24px; height:24px; margin-bottom:5px; }

    .wrapper { min-width:320px; max-width:650px; margin:0 auto; padding:20px; }

    .hero { margin-bottom:30px; }

    .content--block { position:relative; margin-bottom:50px; }
    .content--desc { margin-bottom:32px; position:relative; }
    .content--desc-large { font-size:20px; line-height:26px; }

    .request-id { padding-top:100px; font-size:13px; color:#ccc; }

    @media all and (min-width:500px) {
      body { padding:60px 0; }
      .wrapper { padding:20px 20px 20px 100px; }
      .ico svg { width:40px; height:40px; margin-bottom:0; }
      .hero { margin-bottom:70px; }
      .content--block { margin-bottom:80px; }
      .content--desc .ico { position:absolute; left:-70px; top:5px; }
    }

    @media all and (min-width:900px) {
      .wrapper { padding:20px; }
    }

  </style>
</head>

<body class="status-error status-code-502">

<div class="wrapper">
  <div class="hero">
  </div> <!-- /.hero -->
  <div class="content">
    <div class="content--block">
      <div class="content--desc">
        <i class="ico ico-svg ico-40-svg">
          <svg viewBox="0 0 40 36" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">
            <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
              <g id="back-soon-3" sketch:type="MSArtboardGroup" transform="translate(-230.000000, -519.000000)">
                <g id="what-went-wrong?" sketch:type="MSLayerGroup" transform="translate(231.000000, 444.000000)">
                  <g id="warning" transform="translate(0.000000, 77.000000)" sketch:type="MSShapeGroup">
                    <path d="M17.593,0.492 C18.217,-0.589 19.778,-0.589 20.402,0.492 L37.766,30.567 C38.39,31.648 37.61,33 36.361,33 L1.634,33 C0.386,33 -0.395,31.648 0.229,30.567 L17.593,0.492 L17.593,0.492 Z" id="Stroke-1" stroke="#E9BE33" stroke-width="2" stroke-linejoin="round"></path>
                    <path d="M20.75,28 C20.75,28.966 19.966,29.75 19,29.75 C18.033,29.75 17.25,28.966 17.25,28 C17.25,27.034 18.033,26.25 19,26.25 C19.966,26.25 20.75,27.034 20.75,28" id="Fill-2" fill="#E9BE33"></path>
                    <path d="M19,23 L19,8" id="Stroke-3" stroke="#E9BE33" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                  </g>
                </g>
              </g>
            </g>
          </svg>
        </i>
        <p class="content--desc-large">
          Due to an unexpected technical problem, Shopify Partners is temporarily unavailable. Please check back in a few minutes – we'll be up and running in no time!
        </p>
      </div> <!-- /.content-desc -->
    </div> <!-- /.content-block -->
    <div class="content--block">
      <h3>What can I do?</h3>
      <div class="content--desc">
        <i class="ico ico-svg ico-40-svg">
          <svg viewBox="0 0 40 40" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">
            <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
              <g id="back-soon-3" sketch:type="MSArtboardGroup" transform="translate(-231.000000, -695.000000)" stroke="#96A7B6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <g id="what-can-I-do?" sketch:type="MSLayerGroup" transform="translate(229.000000, 619.000000)">
                  <g id="next-steps---visitor" transform="translate(0.000000, 71.000000)" sketch:type="MSShapeGroup">
                    <path d="M40.625,24.812 C40.625,35.202 32.202,43.624 21.813,43.624 C11.423,43.624 3,35.202 3,24.812 C3,14.422 11.423,6 21.813,6 C32.202,6 40.625,14.422 40.625,24.812 L40.625,24.812 Z M21.813,25.922 L14.813,17.812 L21.813,25.922 Z M31.813,22.812 L21.813,25.922 L31.813,22.812 Z" id="clock"></path>
                  </g>
                </g>
              </g>
            </g>
          </svg>
        </i>
        <h4>If you're a visitor</h4>
        <p>Please try again in 5 or 10 minutes by refreshing the page. Operation engineers are aware of this problem and are working to get it solved. In the meantime, you can keep an eye on the <a href="http://status.shopify.com" target="_blank">status page</a> for updates.</p>
      </div> <!-- /.content-desc -->
    </div> <!-- /.content-block -->
  </div> <!-- /.content -->
</div> <!-- /.wrapper -->
</body>
</html>
```

</details>

## Steps to reproduce the problem

1. create multiple orgnizations
1. asks shopify support to disable some organizations
1. shopify create
1. choose disabled organization

## Specifications

- Operating System: Ubuntu
- Ruby version (ruby -v): 2.6.3

**Comment by tanema** [comment]
Thanks for reporting this, I will look into this soon.

**Comment by tanema** [comment]
Do you have multiple accounts with shopify? If so I recommend running `shopify logout` and then try running create again. It does seem that we do not filter out disabled orgs but there is no reason why a org that you belong to would be missing

**Comment by tanema** [comment]
Do you have multiple accounts with shopify? If so I recommend running `shopify logout` and then try running create again. It does seem that we do not filter out disabled orgs but there is no reason why a org that you belong to would be missing

**Comment by duleorlovic** [comment]
@tanema thanks for helping. I did `shopify logout` and `rm -rf ~/.shopify-app-cli/` several times.
The reason why I created this issue is that my active organization id is 648793 (I noticed that when I log in, url is https://partners.shopify.com/648793/stores ) but when I selected some of the suggested organizations I notice this lines in a log.

(when I select first)
```
? Select organization (You chose: TRK Innovations)
✗ No Development Stores available.                                                                  
Visit https://partners.shopify.com/830170/stores to create one       
```
(when I select second)
```
? Select organization (You chose: TRK INNOVATIONS)
✗ No Development Stores available.                                                                  
Visit https://partners.shopify.com/1538746/stores to create one 
```

As you can see, I had two disabled organizations 830170 and 1538746 , and I can not select my active organization 648793

**Comment by attaboy** [comment]
Side note: it seems like it would be useful to include the organization ID in the list of orgs to choose from, since the name alone may not distinguish it.

**Comment by stephszeto** [comment]
Might be the same underlying problem as: https://github.com/Shopify/shopify-cli/issues/1513

**Comment by hannachen** [comment]
👋 This should be fixed now -- only active organizations will show up, and for most accounts there should only be one, thus removing the need to select an organization at all.
