### ISSUE TITLE
Port to Tunnel

### ISSUE THREAD

**Issue by davidpgero** [Shopify/shopify-cli#731]
# Issue summary

When I create a new tunnel, I'd like to set the port. The best would be some kind of flag from the `.shopify-cli.yml`

Currently, it doesn't work. 

## Expected behavior

Create a tunnel with a given port number

## Actual behavior

I got an error

```bash
$ shopify tunnel start --port 5000                                      
This command ran with ID: 06544
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
  22: from /Users/computer/.shopify-app-cli/bin/shopify:36:in `<main>'
	21: from /Users/computer/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	20: from /Users/computer/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
19: from /Users/computer/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	18: from /Users/computer/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:18:in `call'
	17: from /Users/computer/.shopify-app-cli/lib/shopify-cli/core/monorail.rb:32:in `log'
16: from /Users/computer/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:19:in `block in call'
	15: from /Users/computer/.shopify-app-cli/lib/shopify-cli/core/executor.rb:17:in `call'
	14: from /Users/computer/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
13: from /Users/computer/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	12: from /Users/computer/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	11: from /Users/computer/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
10: from /Users/computer/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	 9: from /Users/computer/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	 8: from /Users/computer/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
7: from /Users/computer/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	 6: from /Users/computer/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	 5: from /Users/computer/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
4: from /Users/computer/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	 3: from /Users/computer/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	 2: from /Users/computer/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
1: from /Users/computer/.shopify-app-cli/lib/shopify-cli/command.rb:20:in `call'
/Users/computer/.shopify-app-cli/lib/shopify-cli/options.rb:21:in `parse': invalid option: --port (OptionParser::InvalidOption)
```

## Steps to reproduce the problem

1. shopify tunnel start --port=5000
2. shopify tunnel start --port 5000

## Specifications

- Operating System: OS X
- Shell: ZSH
- Ruby version (ruby -v): ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin17]

**Comment by tanema** [comment]
Can I ask why you want to set the port?

**Comment by davidpgero** [comment]
👋 @tanema , yes, sure. 

I found it's possible in the codebase so I give it a try. Currently, I'm using `5000` which is default to `foreman`, but I can use `8081`. 👍

**Comment by SirCameron** [comment]
> Can I ask why you want to set the port?

8081 is quite common, used by many tooks. Would be nice to have an option to use a different port.

**Comment by EliJArmstrong** [comment]
I saw this issue here:
https://github.com/Shopify/shopify-cli/issues/1151

I used the last suggestion to change my port number. My file path was a bit different but the post got me to the result I wanted. (Changing the port number)
