### ISSUE TITLE
CLI friction log of a new(bie) user

### ISSUE THREAD

**Issue by igrigorik** [Shopify/shopify-cli#762]
Not an issue per se but some notes on my onboarding flow as someone that's new and doesn't have much prior knowledge about Shopify toolchain. I saw the Unite video on the new CLI, which looked slick and easy to get started with, and it piqued my curiosity to try and take it for a spin. Feel free to take or ignore any of this, in no particular order..

### Finding the [install instructions](https://shopify.github.io/shopify-app-cli/getting-started/install/) was a bit of a maze
The [blog](https://www.shopify.com/partners/blog/cli-tool) leads you to [shopify.dev](https://shopify.dev/concepts/shopify-introduction) which doesn't actually mention CLI but refers to "tools" down the page - OK, click on that - there is a link to the CLI [source on GitHub](url), with a documentation link in the readme — click —  then click again on install instructions - finally.

This was unnecessarily hard. Ideally, a landing page on shopify.dev that explains how to install on various platforms, linked directly from the blog post. 

_Aside: there is something wonky with homebrew installer, which seems to install a shopify rbenv shim which needs to be manually removed to get access to CLI? Not 100% sure if this is installer issue or something in my environment, but it keeps restoring the shim on me — grr._

### ngrok onboarding is nice, but falls down once it times outs
The bundled ngrok binary is a nice touch and works great on first install, but the experience falls apart once the tunnel times out: the CLI doesn't prompt for ngrok auth on first run and doesn't warn you that the tunnel will timeout; once the tunnel times out there is no liveness check in `shopify serve` and it keeps pulling the same (dead) persisted (in `.env`) ngrok url when starting the server. After a bunch of poking around, you finally realize that you have to manually start and stop the tunnel.

The onboarding is nice, but there should be built-in liveness checks for the tunnel to avoid the above pain.

### Problems with Puma after Rails project is created
Project was created with `shopify create` and on first `shopify serve` it immediately crashed due to missing Puma gem. 

```
✓ ngrok tunnel running at https://...
✓ .env saved to project root
✓ Whitelist URLS updated in Partners Dashboard
┏━━ Running server... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in block in materialize': Could not find puma-4.3.5 in any of the sources (Bundler::GemNotFound) ┃	from /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:inmap!'
┃	from /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in materialize' ┃	from /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:inspecs'
┃	from /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in specs_for' ┃	from /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:226:inrequested_specs'
┃	from /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in block in definition_method' ┃	from /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:insetup'
┃	from /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:149:in setup' ┃	from /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:inblock in <top (required)>'
┃	from /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in with_level' ┃	from /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:insilence'
┃	from /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in <top (required)>' ┃	from /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:inrequire'
┃	from /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require' ┃	from /Users/igrigorik/git/vitals/config/boot.rb:3:in<top (required)>'
┃	from bin/rails:3:in require_relative' ┃	from bin/rails:3:in<main>'
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

Not sure what went wrong here TBH, rerunning bundle update seems to have fixed it.

### Missing guidance on webpacker install
Perhaps the implicit assumption is that the developer has node.js and Yarn installed, but this was another debug flow where some upfront guidance could have been helpful. 

```
✓ Whitelist URLS updated in Partners Dashboard
┏━━ Running server... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ => Booting Puma
┃ => Rails 6.0.3.2 application starting in development
┃ => Run `rails server --help` for more startup options
┃ Exiting
┃ /Users/igrigorik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:95:in `rescue in load': Webpacker configuration file not found /Users/igrigorik/git/vitals/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - /Users/igrigorik/git/vitals/config/webpacker.yml (RuntimeError)
```

Heading to Google yielded that I need to install nodejs, Yarn, and then run `rails webpacker:install`. After all that was done, the app booted successfully. Ideally, the CLI should have interrogated my environment and given me guidance on what is missing and how to install it.

### Service errors & confused error messages
I was having all kinds of trouble getting the `serve` command to work at some point, figured I'll do a "logout" and "connect" to ensure my credentials are correct. That then yielded...

```
» shopify serve                                                                                                  
𝒾 Authentication required. Login to the URL below with your Shopify Partners account credentials to continue.
Please open this URL in your browser:
https://accounts.shopify.com/oauth/authorize?...
Traceback (most recent call last):
	25: from /usr/local/Cellar/shopify-cli/1.0.1/src/bin/shopify:30:in `<main>'
	24: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	23: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	22: from /usr/local/Cellar/shopify-cli/1.0.1/src/bin/shopify:31:in `block in <main>'
	21: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/core/entry_point.rb:39:in `call'
	20: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/core/monorail.rb:20:in `log'
	19: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/core/entry_point.rb:40:in `block in call'
	18: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/core/executor.rb:13:in `call'
	17: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/core/executor.rb:13:in `each'
	16: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/core/executor.rb:14:in `block in call'
	15: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/task.rb:7:in `call'
	14: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/tasks/ensure_dev_store.rb:10:in `call'
	13: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/tasks/ensure_dev_store.rb:31:in `shop'
	12: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/partners_api/organizations.rb:6:in `fetch_all'
	11: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/partners_api.rb:48:in `query'
	10: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/partners_api.rb:56:in `authenticated_req'
	 9: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/partners_api.rb:49:in `block in query'
	 8: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/partners_api.rb:67:in `api_client'
	 7: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/partners_api.rb:73:in `access_token'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `get'
	 5: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/db.rb:87:in `get'
	 4: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/partners_api.rb:74:in `block in access_token'
	 3: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/partners_api.rb:86:in `authenticate'
	 2: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/oauth.rb:43:in `authenticate'
	 1: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/oauth.rb:148:in `request_exchange_token'
/usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/oauth.rb:169:in `post_token_request': Invalid 'subject_token' value: invalid (ShopifyCli::OAuth::Error)
```

After beating my head against the desk for a while, I tried to load the partner dashboard in my browser and got "Due to an unexpected technical problem, Shopify Partners is temporarily unavailable. Please check back in a few minutes – we'll be up and running in no time!" — doh.

I didn't dig to validate but my assumption is that the auth request was getting an HTTP error, trying to parse it as oAuth response, and raising exception. Ideally, I should have seen an error stating that the API or service is temporarily unavailable, and that I should come back later.

### Control-T to open store doesn't work

```
✓ Whitelist URLS updated in Partners Dashboard
⭑ Press  Control-T to open this project
load: 0.88  cmd: fsevent_watch 14939 waiting 0.01u 0.04s
┃ Thread TID-owsn0ym2k
┃ Thread: TID-owsn0ym2k
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:334:in `backtrace'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:334:in `block in log_thread_status'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:327:in `each'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:327:in `log_thread_status'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:460:in `block in setup_signals'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/single.rb:117:in `join'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/single.rb:117:in `run'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:172:in `run'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/rack/handler/puma.rb:73:in `run'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:327:in `start'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:39:in `start'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `tap'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `perform'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/command/base.rb:69:in `perform'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/command.rb:46:in `invoke'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
┃ /Users/igrigorik/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
┃ bin/rails:4:in `<main>'
┃ Thread TID-owsn1e12k
┃ Thread: TID-owsn1e12k
Please open this URL in your browser:
https://....
```

### CLI authentication fails after authorizing in browser 
Covered in #751.

---

Hope some of this is useful and helps improve the future experience for other users. All the complaints aside, I can report that I got the app up and running.. it just took a few hours instead of advertised minutes. ;-)

**Comment by mkevinosullivan** [comment]
Hi Ilya, sorry to read that your experience with the CLI was not as expedient (or seamless) as advertised, and thank you for taking the time to provide such detailed feedback that we we will delve into.

Do you mind running `shopify system all` (from within your app project directory) and share the output?  It's a hidden command to help provide environment context to aid our debugging, etc.

Regards, Kevin.

**Comment by igrigorik** [comment]
```
Environment
  TERM              = xterm-256color
  SHELL             = /bin/zsh
  PATH              = /Users/igrigorik/.rbenv/shims:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
  LANG              = en_US.UTF-8

Shopify App CLI
               ROOT = /usr/local/Cellar/shopify-cli/1.0.2/src
  PROJECT_TYPES_DIR = /usr/local/Cellar/shopify-cli/1.0.2/src/lib/project_types
           TEMP_DIR = /usr/local/Cellar/shopify-cli/1.0.2/src/.tmp
          CACHE_DIR = /Users/igrigorik/.cache/shopify
   TOOL_CONFIG_PATH = /Users/igrigorik/.config/shopify
           LOG_FILE = /Users/igrigorik/.config/shopify/logs/log.log
     DEBUG_LOG_FILE = /Users/igrigorik/.config/shopify/logs/debug.log

Ruby (via RbConfig)
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  x86_64-apple-darwin19     - RbConfig["host"]
  ruby-2.6.0                - RbConfig["RUBY_VERSION_NAME"]

Commands
  ✓ git, /usr/local/git/current/bin/git
  ✓ curl, /usr/bin/curl
  ✓ tar, /usr/bin/tar
  ✓ unzip, /usr/bin/unzip

In a Rails project directory
  ✓ gem, /Users/igrigorik/.rbenv/shims/gem, version 3.0.3
  ✓ rails, /Users/igrigorik/.rbenv/shims/rails, version 6.0.3.2
  ✓ rake, /Users/igrigorik/.rbenv/shims/rake, version 13.0.1
  ✓ ruby, /Users/igrigorik/.rbenv/shims/ruby, version 2.6.6p146
  ✓ ngrok, /Users/igrigorik/.cache/shopify/ngrok
```

Let me know if there is anything else that can help.
