### ISSUE TITLE
NoMethodError when creating a new app.

### ISSUE THREAD

**Issue by luilver** [Shopify/shopify-cli#856]
# Issue summary

I have successfully login (after the [aforementioned unexpected behavior](https://github.com/Shopify/shopify-app-cli/issues/855)). Afterwards CLI said: «You have no apps to connect to, creating a new app.». When I filled with my App name script created a `.env` and `.shopify-cli.yml` files with an error.

## Expected behavior

Finish without an error

## Actual behavior

This command ran with ID: 56881
Please include this information in any issues/report along with relevant logs

<details>
Traceback (most recent call last):
        22: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/bin/shopify:32:in `<main>'
        21: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        20: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        19: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/bin/shopify:33:in `block in <main>'
        18: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/lib/shopify-cli/core/entry_point.rb:39:in `call'
        17: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/lib/shopify-cli/core/monorail.rb:32:in `log'
        16: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/lib/shopify-cli/core/entry_point.rb:40:in `block in call'
        15: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/lib/shopify-cli/core/executor.rb:15:in `call'
        14: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        13: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        12: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        11: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        10: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
         9: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
         8: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
         7: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
         6: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/vendor/deps/cli-ui/lib/cli/ui.rb:172:in `log_output_to'
         5: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
         4: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
         3: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
         2: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
         1: from /var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/lib/shopify-cli/command.rb:25:in `call'
/var/lib/gems/2.7.0/gems/shopify-cli-1.1.1/lib/shopify-cli/commands/connect.rb:18:in `call': undefined method `[]' for nil:NilClass (NoMethodError)
</details>

## Steps to reproduce the problem

1. Steps described [here](https://github.com/Shopify/shopify-app-cli/issues/855)
2. Open a ngrok tunnel using `ngrok http 3456`
3. Finish login process (ensures account has no apps to connect to)
4. Create a new app

## Reduced test case

I have no idea how to write a reduced test case but in order to help to understand this I will give you my thoughts:

I'm pretty sure there has something localhost:3456 related which makes the script to fail. Files .env and .shopify-cli.yml are created successfully. If I run `shopify connect` command again it connects successfully to my App.

## Specifications

- App type: Shopify CLI
- Operating System: Ubuntu 20.04 Server
- Shell: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
- Ruby version (ruby -v): ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

**Comment by paulomarg** [comment]
Thank you for the report @luilver! It seems that the `connect` command is failing to detect the newly created app on the first run. We will look into it.

**Comment by luilver** [comment]
My pleasure !

**Comment by luilver** [comment]
> This issue seems inactive. If it's still relevant, please add a comment saying so. Otherwise, take no action.
> 
> → If there's no activity within a week, then a bot will automatically close this.
> 
> Thanks for helping to improve Shopify's dev tooling and experience.

@paulomarg
